// GENERATED by scripts/gen_catalog.py from catalog.json — do not edit.
/**
 * The catalog the agent is shown: Aleph's domain cards plus the A2UI
 * primitives they compose from. Generated from
 * `packages/aleph-a2ui/src/aleph_a2ui/catalog.json`, which is also the source
 * of the Python validator — so the shapes the agent is told about and the
 * shapes the server accepts cannot drift apart.
 */
export const ALEPH_A2UI_CATALOG = {
  "catalogId": "aleph://v1",
  "components": {
    "ApprovalCard": {
      "description": "An approve/reject gate for a consequential action (an agent_action build/connector change, a synthesis proposal, a review finding). Render this when a tool result asks you to surface an approval — the analyst clicks Approve/Reject and the ActionRouter executes. `target_id` + `target_kind` come from the tool result; do not fabricate them.",
      "props": {
        "type": "object",
        "properties": {
          "target_id": {
            "type": "string"
          },
          "target_kind": {
            "type": "string"
          },
          "title": {
            "type": "string"
          },
          "summary": {
            "type": "string"
          },
          "severity": {
            "type": "string",
            "description": "info | low | medium | high"
          },
          "evidence_refs": {
            "type": "array",
            "items": {
              "type": "object"
            }
          },
          "diff_card_id": {
            "type": "string"
          }
        },
        "required": [
          "target_id",
          "target_kind",
          "title",
          "summary"
        ]
      }
    },
    "ArtifactCard": {
      "description": "A built product artifact (report/deck/source-pack) with its status.",
      "props": {
        "type": "object",
        "properties": {
          "artifact_id": {
            "type": "string"
          },
          "short_id": {
            "type": "string"
          },
          "title": {
            "type": "string"
          },
          "artifact_kind": {
            "type": "string"
          },
          "status": {
            "type": "string"
          },
          "drifted": {
            "type": "boolean"
          }
        },
        "required": [
          "artifact_id",
          "title",
          "artifact_kind",
          "status"
        ]
      }
    },
    "ChartCard": {
      "description": "A chart visualizing quantitative data. Provide a self-contained Vega-Lite spec in `vega_lite_spec` with data embedded under `data.values` (array of row objects). Use for comparisons, trends, distributions, or benchmark numbers the analyst asks you to plot.",
      "props": {
        "type": "object",
        "properties": {
          "title": {
            "type": "string"
          },
          "vega_lite_spec": {
            "type": "object",
            "description": "A complete Vega-Lite spec with embedded data."
          },
          "dataset_version_id": {
            "type": "string"
          }
        }
      }
    },
    "ClaimCard": {
      "description": "A single factual claim with its confidence and citations. Use when surfacing one well-scoped assertion grounded in the wiki.",
      "props": {
        "type": "object",
        "properties": {
          "claim_id": {
            "type": "string"
          },
          "text": {
            "type": "string"
          },
          "confidence": {
            "type": "string",
            "enum": [
              "cited",
              "well-supported",
              "weakly-supported",
              "contested",
              "uncited",
              "retracted"
            ]
          },
          "citations": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "marker": {
                  "type": "string"
                },
                "source_short_id": {
                  "type": "string"
                }
              }
            }
          }
        },
        "required": [
          "claim_id",
          "text",
          "confidence"
        ]
      }
    },
    "DiffCard": {
      "description": "A revision diff for a wiki page (from_revision_id → to_revision_id). Render when showing what changed between two wiki revisions. Supply `from_body_md`/`to_body_md` to render a real line diff.",
      "props": {
        "type": "object",
        "properties": {
          "from_revision_id": {
            "type": "string"
          },
          "to_revision_id": {
            "type": "string"
          },
          "page_id": {
            "type": "string"
          },
          "from_body_md": {
            "type": "string"
          },
          "to_body_md": {
            "type": "string"
          }
        },
        "required": [
          "from_revision_id",
          "to_revision_id",
          "page_id"
        ]
      }
    },
    "FindingCard": {
      "description": "A reviewer finding (contradiction, weak source, coverage gap) with a severity.",
      "props": {
        "type": "object",
        "properties": {
          "finding_id": {
            "type": "string"
          },
          "severity": {
            "type": "string",
            "enum": [
              "info",
              "low",
              "medium",
              "high"
            ]
          },
          "kind": {
            "type": "string"
          },
          "summary": {
            "type": "string"
          }
        },
        "required": [
          "finding_id",
          "severity",
          "kind",
          "summary"
        ]
      }
    },
    "FormCard": {
      "description": "A dynamic input form. Use to collect structured input conversationally (parameters, choices) instead of free text. `fields` is an array of field specs ([{name,label,type,options?}]).",
      "props": {
        "type": "object",
        "properties": {
          "form_id": {
            "type": "string"
          },
          "title": {
            "type": "string"
          },
          "fields": {
            "type": "array",
            "items": {
              "type": "object"
            }
          }
        },
        "required": [
          "form_id",
          "title",
          "fields"
        ]
      }
    },
    "HypothesisCard": {
      "description": "A research hypothesis with its current confidence and evidence count.",
      "props": {
        "type": "object",
        "properties": {
          "hypothesis_id": {
            "type": "string"
          },
          "title": {
            "type": "string"
          },
          "confidence": {
            "type": "string"
          },
          "evidence_count": {
            "type": "number"
          }
        },
        "required": [
          "hypothesis_id",
          "title"
        ]
      }
    },
    "SourceCard": {
      "description": "A reference to an ingested source with its processing status.",
      "props": {
        "type": "object",
        "properties": {
          "source_id": {
            "type": "string"
          },
          "short_id": {
            "type": "string"
          },
          "title": {
            "type": "string"
          },
          "url": {
            "type": "string"
          },
          "status": {
            "type": "string"
          },
          "normalized_preview": {
            "type": "string"
          }
        },
        "required": [
          "source_id",
          "short_id",
          "title",
          "status"
        ]
      }
    },
    "TableCard": {
      "description": "A sortable, filterable data table. Provide `columns` ([{name,label}]) and `rows` (array of objects keyed by column name).",
      "props": {
        "type": "object",
        "properties": {
          "title": {
            "type": "string"
          },
          "columns": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "name": {
                  "type": "string"
                },
                "label": {
                  "type": "string"
                }
              },
              "required": [
                "name"
              ]
            }
          },
          "rows": {
            "type": "array",
            "items": {
              "type": "object"
            }
          }
        }
      }
    },
    "Button": {
      "description": "A clickable button. `child` is the id of its label component.",
      "props": {
        "type": "object",
        "properties": {
          "child": {
            "type": "string"
          }
        },
        "additionalProperties": true
      }
    },
    "Card": {
      "description": "A bordered container wrapping one child component (id in `child`).",
      "props": {
        "type": "object",
        "properties": {
          "child": {
            "type": "string"
          }
        },
        "additionalProperties": true
      }
    },
    "Column": {
      "description": "A vertical stack of child components (referenced by id in `children`).",
      "props": {
        "type": "object",
        "properties": {
          "children": {
            "type": "array",
            "items": {
              "type": "string"
            }
          }
        },
        "additionalProperties": true
      }
    },
    "Divider": {
      "description": "A separator between sections.",
      "props": {
        "type": "object",
        "additionalProperties": true
      }
    },
    "Icon": {
      "description": "A named icon (`name`).",
      "props": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string"
          }
        },
        "additionalProperties": true
      }
    },
    "Image": {
      "description": "An image. `url` is the source.",
      "props": {
        "type": "object",
        "properties": {
          "url": {
            "type": "string"
          }
        },
        "additionalProperties": true
      }
    },
    "List": {
      "description": "A list of child components (ids in `children`).",
      "props": {
        "type": "object",
        "properties": {
          "children": {
            "type": "array",
            "items": {
              "type": "string"
            }
          }
        },
        "additionalProperties": true
      }
    },
    "Row": {
      "description": "A horizontal arrangement of child components (ids in `children`).",
      "props": {
        "type": "object",
        "properties": {
          "children": {
            "type": "array",
            "items": {
              "type": "string"
            }
          }
        },
        "additionalProperties": true
      }
    },
    "Text": {
      "description": "A run of text. `text` is the string; `variant` sets heading/body style.",
      "props": {
        "type": "object",
        "properties": {
          "text": {
            "type": "string"
          },
          "variant": {
            "type": "string"
          }
        },
        "required": [
          "text"
        ],
        "additionalProperties": true
      }
    }
  }
} as const;
