// GENERATED by scripts/gen_catalog.py from catalog.json + render_catalog.generated.json — do not edit.
/**
 * The catalog the agent is shown: every component
 * `apps/web/src/a2ui/aleph-catalog-v09.tsx` can render, in the A2UI v0.9 wire
 * shape the agent must produce — `{ id, component, ...props }`, props inline.
 *
 * Two sources, one output. The component set and the prop schemas are
 * EXTRACTED from the renderer's own zod schemas
 * (`packages/aleph-a2ui/tools/extract_render_catalog.mjs` ->
 * `render_catalog.generated.json`); the descriptions come from
 * `packages/aleph-a2ui/src/aleph_a2ui/catalog.json`, the one file a human
 * edits. So the shapes the agent is told about, the shapes the browser draws
 * and the shapes `aleph_a2ui.catalog.validate_component` accepts cannot drift.
 *
 * `required` and `properties` sit at the top level of each entry deliberately:
 * that is where `@ag-ui/a2ui-toolkit`'s `validateA2UIComponents` looks when the
 * A2UI middleware decides whether to paint a surface or ask the model to try
 * again. Nested under an `allOf` wrapper — the upstream inline-catalog shape —
 * both are invisible and validation quietly degrades to a name check.
 */
export const ALEPH_A2UI_CATALOG = {
  "catalogId": "aleph://v1",
  "$defs": {
    "ComponentId": {
      "type": "string",
      "description": "The unique identifier for a component, used for both definitions and references within the same surface."
    },
    "AccessibilityAttributes": {
      "type": "object",
      "description": "Attributes to enhance accessibility when using assistive technologies like screen readers.",
      "properties": {
        "label": {
          "$ref": "#/$defs/DynamicString",
          "description": "A short string, typically 1 to 3 words, used by assistive technologies to convey the purpose or intent of an element. For example, an input field might have an accessible label of 'User ID' or a button might be labeled 'Submit'."
        },
        "description": {
          "$ref": "#/$defs/DynamicString",
          "description": "Additional information provided by assistive technologies about an element such as instructions, format requirements, or result of an action. For example, a mute button might have a label of 'Mute' and a description of 'Silences notifications about this conversation'."
        }
      }
    },
    "ComponentCommon": {
      "type": "object",
      "properties": {
        "id": {
          "$ref": "#/$defs/ComponentId"
        },
        "accessibility": {
          "$ref": "#/$defs/AccessibilityAttributes"
        }
      },
      "required": [
        "id"
      ]
    },
    "ChildList": {
      "oneOf": [
        {
          "type": "array",
          "items": {
            "$ref": "#/$defs/ComponentId"
          },
          "description": "A static list of child component IDs."
        },
        {
          "type": "object",
          "description": "A template for generating a dynamic list of children from a data model list. The `componentId` is the component to use as a template.",
          "properties": {
            "componentId": {
              "$ref": "#/$defs/ComponentId"
            },
            "path": {
              "type": "string",
              "description": "The path to the list of component property objects in the data model."
            }
          },
          "required": [
            "componentId",
            "path"
          ],
          "additionalProperties": false
        }
      ]
    },
    "DataBinding": {
      "type": "object",
      "properties": {
        "path": {
          "type": "string",
          "description": "A JSON Pointer path to a value in the data model."
        }
      },
      "required": [
        "path"
      ],
      "additionalProperties": false
    },
    "DynamicValue": {
      "description": "A value that can be a literal, a path, or a function call returning any type.",
      "oneOf": [
        {
          "type": "string"
        },
        {
          "type": "number"
        },
        {
          "type": "boolean"
        },
        {
          "type": "array"
        },
        {
          "$ref": "#/$defs/DataBinding"
        },
        {
          "$ref": "#/$defs/FunctionCall"
        }
      ]
    },
    "DynamicString": {
      "description": "Represents a string",
      "oneOf": [
        {
          "type": "string"
        },
        {
          "$ref": "#/$defs/DataBinding"
        },
        {
          "allOf": [
            {
              "$ref": "#/$defs/FunctionCall"
            },
            {
              "properties": {
                "returnType": {
                  "const": "string"
                }
              }
            }
          ]
        }
      ]
    },
    "DynamicNumber": {
      "description": "Represents a value that can be either a literal number, a path to a number in the data model, or a function call returning a number.",
      "oneOf": [
        {
          "type": "number"
        },
        {
          "$ref": "#/$defs/DataBinding"
        },
        {
          "allOf": [
            {
              "$ref": "#/$defs/FunctionCall"
            },
            {
              "properties": {
                "returnType": {
                  "const": "number"
                }
              }
            }
          ]
        }
      ]
    },
    "DynamicBoolean": {
      "description": "A boolean value that can be a literal, a path, or a function call returning a boolean.",
      "oneOf": [
        {
          "type": "boolean"
        },
        {
          "$ref": "#/$defs/DataBinding"
        },
        {
          "allOf": [
            {
              "$ref": "#/$defs/FunctionCall"
            },
            {
              "properties": {
                "returnType": {
                  "const": "boolean"
                }
              }
            }
          ]
        }
      ]
    },
    "DynamicStringList": {
      "description": "Represents a value that can be either a literal array of strings, a path to a string array in the data model, or a function call returning a string array.",
      "oneOf": [
        {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        {
          "$ref": "#/$defs/DataBinding"
        },
        {
          "allOf": [
            {
              "$ref": "#/$defs/FunctionCall"
            },
            {
              "properties": {
                "returnType": {
                  "const": "array"
                }
              }
            }
          ]
        }
      ]
    },
    "FunctionCall": {
      "type": "object",
      "description": "Invokes a named function on the client.",
      "properties": {
        "call": {
          "type": "string",
          "description": "The name of the function to call."
        },
        "args": {
          "type": "object",
          "description": "Arguments passed to the function.",
          "additionalProperties": {
            "anyOf": [
              {
                "$ref": "#/$defs/DynamicValue"
              },
              {
                "type": "object",
                "description": "A literal object argument (e.g. configuration)."
              }
            ]
          }
        },
        "returnType": {
          "type": "string",
          "description": "The expected return type of the function call.",
          "enum": [
            "string",
            "number",
            "boolean",
            "array",
            "object",
            "any",
            "void"
          ],
          "default": "boolean"
        }
      },
      "required": [
        "call"
      ]
    },
    "CheckRule": {
      "type": "object",
      "description": "A single validation rule applied to an input component.",
      "properties": {
        "condition": {
          "$ref": "#/$defs/DynamicBoolean"
        },
        "message": {
          "type": "string",
          "description": "The error message to display if the check fails."
        }
      },
      "required": [
        "condition",
        "message"
      ],
      "additionalProperties": false
    },
    "Checkable": {
      "description": "Properties for components that support client-side checks.",
      "type": "object",
      "properties": {
        "checks": {
          "type": "array",
          "description": "A list of checks to perform. These are function calls that must return a boolean indicating validity.",
          "items": {
            "$ref": "#/$defs/CheckRule"
          }
        }
      }
    },
    "Action": {
      "description": "Defines an interaction handler that can either trigger a server-side event or execute a local client-side function.",
      "oneOf": [
        {
          "type": "object",
          "description": "Triggers a server-side event.",
          "properties": {
            "event": {
              "type": "object",
              "description": "The event to dispatch to the server.",
              "properties": {
                "name": {
                  "type": "string",
                  "description": "The name of the action to be dispatched to the server."
                },
                "context": {
                  "type": "object",
                  "description": "A JSON object containing the key-value pairs for the action context. Values can be literals or paths. Use literal values unless the value must be dynamically bound to the data model. Do NOT use paths for static IDs.",
                  "additionalProperties": {
                    "$ref": "#/$defs/DynamicValue"
                  }
                }
              },
              "required": [
                "name"
              ],
              "additionalProperties": false
            }
          },
          "required": [
            "event"
          ],
          "additionalProperties": false
        },
        {
          "type": "object",
          "description": "Executes a local client-side function.",
          "properties": {
            "functionCall": {
              "$ref": "#/$defs/FunctionCall"
            }
          },
          "required": [
            "functionCall"
          ],
          "additionalProperties": false
        }
      ]
    }
  },
  "components": {
    "ApprovalCard": {
      "description": "An approve/reject gate for a consequential action (an agent_action build/connector change, a synthesis proposal, a review finding). Render this when a tool result asks you to surface an approval — the analyst clicks Approve/Reject and the ActionRouter executes. `target_id` + `target_kind` come from the tool result; do not fabricate them.",
      "type": "object",
      "properties": {
        "id": {
          "$ref": "#/$defs/ComponentId"
        },
        "component": {
          "const": "ApprovalCard"
        },
        "target_id": {
          "$ref": "#/$defs/DynamicString"
        },
        "target_kind": {
          "$ref": "#/$defs/DynamicString",
          "enum": [
            "synthesis_proposal",
            "review_finding",
            "wiki_revision",
            "agent_action",
            "refresh_result"
          ]
        },
        "title": {
          "$ref": "#/$defs/DynamicString"
        },
        "summary": {
          "$ref": "#/$defs/DynamicString"
        },
        "severity": {
          "$ref": "#/$defs/DynamicString",
          "description": "info | low | medium | high",
          "enum": [
            "info",
            "low",
            "medium",
            "high"
          ]
        },
        "evidence_refs": {
          "type": "array"
        },
        "approve_action": {
          "$ref": "#/$defs/Action"
        },
        "reject_action": {
          "$ref": "#/$defs/Action"
        }
      },
      "required": [
        "id",
        "component",
        "target_id",
        "target_kind",
        "title",
        "summary"
      ]
    },
    "ArtifactCard": {
      "description": "A built product artifact (report/deck/source-pack) with its status.",
      "type": "object",
      "properties": {
        "id": {
          "$ref": "#/$defs/ComponentId"
        },
        "component": {
          "const": "ArtifactCard"
        },
        "artifact_id": {
          "$ref": "#/$defs/DynamicString"
        },
        "short_id": {
          "$ref": "#/$defs/DynamicString"
        },
        "title": {
          "$ref": "#/$defs/DynamicString"
        },
        "artifact_kind": {
          "$ref": "#/$defs/DynamicString"
        },
        "status": {
          "$ref": "#/$defs/DynamicString"
        },
        "drifted": {
          "$ref": "#/$defs/DynamicBoolean"
        },
        "open_action": {
          "$ref": "#/$defs/Action"
        }
      },
      "required": [
        "id",
        "component",
        "artifact_id",
        "title",
        "artifact_kind",
        "status"
      ]
    },
    "ArtifactsSurface": {
      "description": "Server-built. Aleph's own code composes this from live project state; do not emit one yourself. Listed here so you can read and reason about a surface you were given.",
      "type": "object",
      "properties": {
        "id": {
          "$ref": "#/$defs/ComponentId"
        },
        "component": {
          "const": "ArtifactsSurface"
        },
        "sources": {
          "$ref": "#/$defs/DynamicValue"
        },
        "artifacts": {
          "$ref": "#/$defs/DynamicValue"
        }
      },
      "required": [
        "id",
        "component"
      ]
    },
    "AudioPlayer": {
      "description": "An audio player for a `url`. Use for a recording or a spoken source; for anything visual use Video or Image.",
      "type": "object",
      "properties": {
        "id": {
          "$ref": "#/$defs/ComponentId"
        },
        "component": {
          "const": "AudioPlayer"
        },
        "url": {
          "anyOf": [
            {
              "type": "string"
            },
            {
              "$ref": "#/$defs/DataBinding",
              "description": "A JSON Pointer path to a value in the data model."
            },
            {
              "$ref": "#/$defs/FunctionCall"
            }
          ],
          "description": "The URL of the audio to be played."
        },
        "description": {
          "anyOf": [
            {
              "type": "string"
            },
            {
              "$ref": "#/$defs/DataBinding",
              "description": "A JSON Pointer path to a value in the data model."
            },
            {
              "$ref": "#/$defs/FunctionCall"
            }
          ],
          "description": "A description of the audio, such as a title or summary."
        }
      },
      "required": [
        "id",
        "component",
        "url"
      ]
    },
    "BriefsSurface": {
      "description": "Server-built. Aleph's own code composes this from live project state; do not emit one yourself. Listed here so you can read and reason about a surface you were given.",
      "type": "object",
      "properties": {
        "id": {
          "$ref": "#/$defs/ComponentId"
        },
        "component": {
          "const": "BriefsSurface"
        },
        "badge_count": {
          "$ref": "#/$defs/DynamicNumber"
        },
        "children": {
          "type": "array"
        }
      },
      "required": [
        "id",
        "component"
      ]
    },
    "Button": {
      "description": "A clickable button. `child` is the id of its label component.",
      "type": "object",
      "properties": {
        "id": {
          "$ref": "#/$defs/ComponentId"
        },
        "component": {
          "const": "Button"
        },
        "child": {
          "type": "string",
          "description": "The ID of the child component. Use a 'Text' component for a labeled button. Only use an 'Icon' if the requirements explicitly ask for an icon-only button. Do NOT define the child component inline."
        },
        "variant": {
          "type": "string",
          "enum": [
            "default",
            "primary",
            "borderless"
          ],
          "default": "default",
          "description": "A hint for the button style. If omitted, a default button style is used. 'primary' indicates this is the main call-to-action button. 'borderless' means the button has no visual border or background, making its child content appear like a clickable link."
        },
        "action": {
          "$ref": "#/$defs/Action"
        },
        "checks": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/CheckRule",
            "description": "A check rule consisting of a condition and an error message."
          },
          "description": "A list of checks to perform."
        }
      },
      "required": [
        "id",
        "component",
        "child",
        "action"
      ]
    },
    "Card": {
      "description": "A bordered container wrapping one child component (id in `child`).",
      "type": "object",
      "properties": {
        "id": {
          "$ref": "#/$defs/ComponentId"
        },
        "component": {
          "const": "Card"
        },
        "child": {
          "type": "string",
          "description": "The ID of the single child component to be rendered inside the card. To display multiple elements, you MUST wrap them in a layout component (like Column or Row) and pass that container's ID here. Do NOT pass multiple IDs or a non-existent ID. Do NOT define the child component inline."
        }
      },
      "required": [
        "id",
        "component",
        "child"
      ]
    },
    "ChartCard": {
      "description": "A chart visualizing quantitative data. Provide a self-contained Vega-Lite spec in `vega_lite_spec` with data embedded under `data.values` (array of row objects). Use for comparisons, trends, distributions, or benchmark numbers the analyst asks you to plot.",
      "type": "object",
      "properties": {
        "id": {
          "$ref": "#/$defs/ComponentId"
        },
        "component": {
          "const": "ChartCard"
        },
        "title": {
          "$ref": "#/$defs/DynamicString"
        },
        "chart_id": {
          "$ref": "#/$defs/DynamicString"
        },
        "vega_lite_spec": {
          "description": "A complete Vega-Lite spec with embedded data."
        }
      },
      "required": [
        "id",
        "component"
      ]
    },
    "CheckBox": {
      "description": "A single on/off switch with a `label`. Bind `value` to a boolean in the data model. For a set of choices use ChoicePicker, not a row of these.",
      "type": "object",
      "properties": {
        "id": {
          "$ref": "#/$defs/ComponentId"
        },
        "component": {
          "const": "CheckBox"
        },
        "label": {
          "anyOf": [
            {
              "type": "string"
            },
            {
              "$ref": "#/$defs/DataBinding",
              "description": "A JSON Pointer path to a value in the data model."
            },
            {
              "$ref": "#/$defs/FunctionCall"
            }
          ],
          "description": "The text to display next to the checkbox."
        },
        "value": {
          "anyOf": [
            {
              "type": "boolean"
            },
            {
              "$ref": "#/$defs/DataBinding",
              "description": "A JSON Pointer path to a value in the data model."
            },
            {
              "$ref": "#/$defs/FunctionCall"
            }
          ],
          "description": "The current state of the checkbox (true for checked, false for unchecked)."
        },
        "checks": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/CheckRule",
            "description": "A check rule consisting of a condition and an error message."
          },
          "description": "A list of checks to perform."
        }
      },
      "required": [
        "id",
        "component",
        "label",
        "value"
      ]
    },
    "ChoicePicker": {
      "description": "Pick from a fixed list of `options` ({label, value}). `variant: mutuallyExclusive` is a radio group / dropdown, `multipleSelection` is a multi-select; `value` binds to an ARRAY of the selected values in both cases. Use this rather than free text whenever the accepted values are known.",
      "type": "object",
      "properties": {
        "id": {
          "$ref": "#/$defs/ComponentId"
        },
        "component": {
          "const": "ChoicePicker"
        },
        "label": {
          "anyOf": [
            {
              "type": "string"
            },
            {
              "$ref": "#/$defs/DataBinding",
              "description": "A JSON Pointer path to a value in the data model."
            },
            {
              "$ref": "#/$defs/FunctionCall"
            }
          ],
          "description": "The label for the group of options."
        },
        "variant": {
          "type": "string",
          "enum": [
            "multipleSelection",
            "mutuallyExclusive"
          ],
          "default": "mutuallyExclusive",
          "description": "A hint for how the choice picker should be displayed and behave."
        },
        "options": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "label": {
                "anyOf": [
                  {
                    "type": "string"
                  },
                  {
                    "$ref": "#/$defs/DataBinding",
                    "description": "A JSON Pointer path to a value in the data model."
                  },
                  {
                    "$ref": "#/$defs/FunctionCall"
                  }
                ],
                "description": "The text to display for this option."
              },
              "value": {
                "type": "string",
                "description": "The stable value associated with this option."
              }
            },
            "required": [
              "label",
              "value"
            ],
            "additionalProperties": false
          },
          "description": "The list of available options to choose from."
        },
        "value": {
          "anyOf": [
            {
              "type": "array",
              "items": {
                "type": "string"
              }
            },
            {
              "$ref": "#/$defs/DataBinding",
              "description": "A JSON Pointer path to a value in the data model."
            },
            {
              "$ref": "#/$defs/FunctionCall"
            }
          ],
          "description": "The list of currently selected values. This should be bound to a string array in the data model."
        },
        "displayStyle": {
          "type": "string",
          "enum": [
            "checkbox",
            "chips"
          ],
          "default": "checkbox",
          "description": "The display style of the component."
        },
        "filterable": {
          "type": "boolean",
          "default": false,
          "description": "If true, displays a search input to filter the options."
        },
        "checks": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/CheckRule",
            "description": "A check rule consisting of a condition and an error message."
          },
          "description": "A list of checks to perform."
        }
      },
      "required": [
        "id",
        "component",
        "options",
        "value"
      ]
    },
    "ClaimCard": {
      "description": "A single factual claim with its confidence and citations. Use when surfacing one well-scoped assertion grounded in the wiki.",
      "type": "object",
      "properties": {
        "id": {
          "$ref": "#/$defs/ComponentId"
        },
        "component": {
          "const": "ClaimCard"
        },
        "claim_id": {
          "$ref": "#/$defs/DynamicString"
        },
        "text": {
          "$ref": "#/$defs/DynamicString"
        },
        "confidence": {
          "$ref": "#/$defs/DynamicString",
          "enum": [
            "under_investigation",
            "weakly_supported",
            "well_supported",
            "contested",
            "refuted",
            "abandoned"
          ]
        },
        "citations": {
          "type": "array"
        },
        "open_action": {
          "$ref": "#/$defs/Action"
        }
      },
      "required": [
        "id",
        "component",
        "claim_id",
        "text",
        "confidence"
      ]
    },
    "Column": {
      "description": "A vertical stack of child components (referenced by id in `children`).",
      "type": "object",
      "properties": {
        "id": {
          "$ref": "#/$defs/ComponentId"
        },
        "component": {
          "const": "Column"
        },
        "children": {
          "anyOf": [
            {
              "type": "array",
              "items": {
                "$ref": "#/$defs/ComponentId",
                "description": "The unique identifier for a component."
              },
              "description": "A static list of child component IDs."
            },
            {
              "type": "object",
              "properties": {
                "componentId": {
                  "$ref": "#/$defs/ComponentId",
                  "description": "The unique identifier for a component."
                },
                "path": {
                  "type": "string",
                  "description": "The path to the list of component property objects in the data model."
                }
              },
              "required": [
                "componentId",
                "path"
              ],
              "additionalProperties": false,
              "description": "A template for generating a dynamic list of children."
            }
          ],
          "description": "Defines the children. Use an array of strings for a fixed set of children, or a template object to generate children from a data list. Children cannot be defined inline, they must be referred to by ID."
        },
        "justify": {
          "type": "string",
          "enum": [
            "start",
            "center",
            "end",
            "spaceBetween",
            "spaceAround",
            "spaceEvenly",
            "stretch"
          ],
          "default": "start",
          "description": "Defines the arrangement of children along the main axis (vertically). Use 'spaceBetween' to push items to the edges (e.g. header at top, footer at bottom), or 'start'/'end'/'center' to pack them together."
        },
        "align": {
          "type": "string",
          "enum": [
            "center",
            "end",
            "start",
            "stretch"
          ],
          "default": "stretch",
          "description": "Defines the alignment of children along the cross axis (horizontally). This is similar to the CSS 'align-items' property."
        }
      },
      "required": [
        "id",
        "component",
        "children"
      ]
    },
    "DateTimeInput": {
      "description": "A date and/or time picker. Set `enableDate` / `enableTime` for which halves are offered; `value` is an ISO 8601 string, seeded with \"\" when unset.",
      "type": "object",
      "properties": {
        "id": {
          "$ref": "#/$defs/ComponentId"
        },
        "component": {
          "const": "DateTimeInput"
        },
        "value": {
          "anyOf": [
            {
              "type": "string"
            },
            {
              "$ref": "#/$defs/DataBinding",
              "description": "A JSON Pointer path to a value in the data model."
            },
            {
              "$ref": "#/$defs/FunctionCall"
            }
          ],
          "description": "The selected date and/or time value in ISO 8601 format. If not yet set, initialize with an empty string."
        },
        "enableDate": {
          "type": "boolean",
          "default": false,
          "description": "If true, allows the user to select a date."
        },
        "enableTime": {
          "type": "boolean",
          "default": false,
          "description": "If true, allows the user to select a time."
        },
        "min": {
          "anyOf": [
            {
              "$ref": "#/$defs/DynamicString"
            },
            {
              "type": "string",
              "format": "date"
            },
            {
              "type": "string",
              "format": "time"
            },
            {
              "type": "string",
              "format": "date-time"
            }
          ],
          "description": "The minimum allowed date/time in ISO 8601 format."
        },
        "max": {
          "anyOf": [
            {
              "$ref": "#/$defs/DynamicString"
            },
            {
              "type": "string",
              "format": "date"
            },
            {
              "type": "string",
              "format": "time"
            },
            {
              "type": "string",
              "format": "date-time"
            }
          ],
          "description": "The maximum allowed date/time in ISO 8601 format."
        },
        "label": {
          "anyOf": [
            {
              "type": "string"
            },
            {
              "$ref": "#/$defs/DataBinding",
              "description": "A JSON Pointer path to a value in the data model."
            },
            {
              "$ref": "#/$defs/FunctionCall"
            }
          ],
          "description": "The text label for the input field."
        },
        "checks": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/CheckRule",
            "description": "A check rule consisting of a condition and an error message."
          },
          "description": "A list of checks to perform."
        }
      },
      "required": [
        "id",
        "component",
        "value"
      ]
    },
    "DiffCard": {
      "description": "A revision diff for a wiki page (from_revision_id → to_revision_id). Render when showing what changed between two wiki revisions. Supply `from_body_md`/`to_body_md` to render a real line diff.",
      "type": "object",
      "properties": {
        "id": {
          "$ref": "#/$defs/ComponentId"
        },
        "component": {
          "const": "DiffCard"
        },
        "from_revision_id": {
          "$ref": "#/$defs/DynamicString"
        },
        "to_revision_id": {
          "$ref": "#/$defs/DynamicString"
        },
        "page_id": {
          "$ref": "#/$defs/DynamicString"
        },
        "from_body_md": {
          "$ref": "#/$defs/DynamicString"
        },
        "to_body_md": {
          "$ref": "#/$defs/DynamicString"
        }
      },
      "required": [
        "id",
        "component",
        "from_revision_id",
        "to_revision_id",
        "page_id"
      ]
    },
    "Divider": {
      "description": "A separator between sections.",
      "type": "object",
      "properties": {
        "id": {
          "$ref": "#/$defs/ComponentId"
        },
        "component": {
          "const": "Divider"
        },
        "axis": {
          "type": "string",
          "enum": [
            "horizontal",
            "vertical"
          ],
          "default": "horizontal",
          "description": "The orientation of the divider."
        }
      },
      "required": [
        "id",
        "component"
      ]
    },
    "FindingCard": {
      "description": "A reviewer finding (contradiction, weak source, coverage gap) with a severity.",
      "type": "object",
      "properties": {
        "id": {
          "$ref": "#/$defs/ComponentId"
        },
        "component": {
          "const": "FindingCard"
        },
        "finding_id": {
          "$ref": "#/$defs/DynamicString"
        },
        "severity": {
          "$ref": "#/$defs/DynamicString",
          "enum": [
            "info",
            "low",
            "medium",
            "high"
          ]
        },
        "kind": {
          "$ref": "#/$defs/DynamicString"
        },
        "summary": {
          "$ref": "#/$defs/DynamicString"
        },
        "evidence_refs": {
          "type": "array"
        },
        "open_action": {
          "$ref": "#/$defs/Action"
        },
        "approve_action": {
          "$ref": "#/$defs/Action"
        },
        "reject_action": {
          "$ref": "#/$defs/Action"
        }
      },
      "required": [
        "id",
        "component",
        "finding_id",
        "severity",
        "kind",
        "summary"
      ]
    },
    "FormCard": {
      "description": "A dynamic input form. Use to collect structured input conversationally (parameters, choices) instead of free text. `fields` is an array of field specs ([{name,label,type,options?}]).",
      "type": "object",
      "properties": {
        "id": {
          "$ref": "#/$defs/ComponentId"
        },
        "component": {
          "const": "FormCard"
        },
        "form_id": {
          "$ref": "#/$defs/DynamicString"
        },
        "title": {
          "$ref": "#/$defs/DynamicString"
        },
        "fields": {
          "type": "array"
        },
        "submit_action": {
          "$ref": "#/$defs/Action"
        }
      },
      "required": [
        "id",
        "component",
        "form_id",
        "title",
        "fields"
      ]
    },
    "GroundingSurface": {
      "description": "Server-built. Aleph's own code composes this from live project state; do not emit one yourself. Listed here so you can read and reason about a surface you were given.",
      "type": "object",
      "properties": {
        "id": {
          "$ref": "#/$defs/ComponentId"
        },
        "component": {
          "const": "GroundingSurface"
        },
        "claim": {
          "$ref": "#/$defs/DynamicValue"
        },
        "groundings": {
          "$ref": "#/$defs/DynamicValue"
        },
        "children": {
          "type": "array"
        }
      },
      "required": [
        "id",
        "component"
      ]
    },
    "HtmlDocCard": {
      "description": "Server-built. Aleph's own code composes this from live project state; do not emit one yourself. Listed here so you can read and reason about a surface you were given.",
      "type": "object",
      "properties": {
        "id": {
          "$ref": "#/$defs/ComponentId"
        },
        "component": {
          "const": "HtmlDocCard"
        },
        "src": {
          "$ref": "#/$defs/DynamicString"
        },
        "title": {
          "$ref": "#/$defs/DynamicString"
        },
        "derived": {
          "$ref": "#/$defs/DynamicBoolean"
        },
        "read_only": {
          "$ref": "#/$defs/DynamicBoolean"
        }
      },
      "required": [
        "id",
        "component",
        "src"
      ]
    },
    "HtmlFrameCard": {
      "description": "Server-built. Aleph's own code composes this from live project state; do not emit one yourself. Listed here so you can read and reason about a surface you were given.",
      "type": "object",
      "properties": {
        "id": {
          "$ref": "#/$defs/ComponentId"
        },
        "component": {
          "const": "HtmlFrameCard"
        },
        "src": {
          "$ref": "#/$defs/DynamicString"
        },
        "title": {
          "$ref": "#/$defs/DynamicString"
        }
      },
      "required": [
        "id",
        "component",
        "src"
      ]
    },
    "Icon": {
      "description": "A named icon (`name`).",
      "type": "object",
      "properties": {
        "id": {
          "$ref": "#/$defs/ComponentId"
        },
        "component": {
          "const": "Icon"
        },
        "name": {
          "anyOf": [
            {
              "type": "string",
              "enum": [
                "accountCircle",
                "add",
                "arrowBack",
                "arrowForward",
                "attachFile",
                "calendarToday",
                "call",
                "camera",
                "check",
                "close",
                "delete",
                "download",
                "edit",
                "event",
                "error",
                "fastForward",
                "favorite",
                "favoriteOff",
                "folder",
                "help",
                "home",
                "info",
                "locationOn",
                "lock",
                "lockOpen",
                "mail",
                "menu",
                "moreVert",
                "moreHoriz",
                "notificationsOff",
                "notifications",
                "pause",
                "payment",
                "person",
                "phone",
                "photo",
                "play",
                "print",
                "refresh",
                "rewind",
                "search",
                "send",
                "settings",
                "share",
                "shoppingCart",
                "skipNext",
                "skipPrevious",
                "star",
                "starHalf",
                "starOff",
                "stop",
                "upload",
                "visibility",
                "visibilityOff",
                "volumeDown",
                "volumeMute",
                "volumeOff",
                "volumeUp",
                "warning"
              ]
            },
            {
              "type": "object",
              "properties": {
                "svgPath": {
                  "type": "string",
                  "description": "Custom SVG path data"
                }
              },
              "required": [
                "svgPath"
              ],
              "additionalProperties": false
            },
            {
              "type": "object",
              "properties": {
                "path": {
                  "type": "string"
                }
              },
              "required": [
                "path"
              ],
              "additionalProperties": false
            }
          ],
          "description": "The name of the icon to display."
        }
      },
      "required": [
        "id",
        "component",
        "name"
      ]
    },
    "Image": {
      "description": "An image. `url` is the source.",
      "type": "object",
      "properties": {
        "id": {
          "$ref": "#/$defs/ComponentId"
        },
        "component": {
          "const": "Image"
        },
        "url": {
          "anyOf": [
            {
              "type": "string"
            },
            {
              "$ref": "#/$defs/DataBinding",
              "description": "A JSON Pointer path to a value in the data model."
            },
            {
              "$ref": "#/$defs/FunctionCall"
            }
          ],
          "description": "The URL of the image to display."
        },
        "description": {
          "anyOf": [
            {
              "type": "string"
            },
            {
              "$ref": "#/$defs/DataBinding",
              "description": "A JSON Pointer path to a value in the data model."
            },
            {
              "$ref": "#/$defs/FunctionCall"
            }
          ],
          "description": "The accessibility description of the image."
        },
        "fit": {
          "type": "string",
          "enum": [
            "contain",
            "cover",
            "fill",
            "none",
            "scaleDown"
          ],
          "default": "fill",
          "description": "Specifies how the image should be resized to fit its container. This corresponds to the CSS 'object-fit' property."
        },
        "variant": {
          "type": "string",
          "enum": [
            "icon",
            "avatar",
            "smallFeature",
            "mediumFeature",
            "largeFeature",
            "header"
          ],
          "default": "mediumFeature",
          "description": "A hint for the image size and style."
        }
      },
      "required": [
        "id",
        "component",
        "url"
      ]
    },
    "ImageCard": {
      "description": "Server-built. Aleph's own code composes this from live project state; do not emit one yourself. Listed here so you can read and reason about a surface you were given.",
      "type": "object",
      "properties": {
        "id": {
          "$ref": "#/$defs/ComponentId"
        },
        "component": {
          "const": "ImageCard"
        },
        "src": {
          "$ref": "#/$defs/DynamicString"
        },
        "title": {
          "$ref": "#/$defs/DynamicString"
        },
        "alt": {
          "$ref": "#/$defs/DynamicString"
        }
      },
      "required": [
        "id",
        "component",
        "src"
      ]
    },
    "InspectorSurface": {
      "description": "Server-built. Aleph's own code composes this from live project state; do not emit one yourself. Listed here so you can read and reason about a surface you were given.",
      "type": "object",
      "properties": {
        "id": {
          "$ref": "#/$defs/ComponentId"
        },
        "component": {
          "const": "InspectorSurface"
        },
        "runs": {
          "$ref": "#/$defs/DynamicValue"
        },
        "selected": {
          "$ref": "#/$defs/DynamicValue"
        },
        "events": {
          "$ref": "#/$defs/DynamicValue"
        },
        "children": {
          "type": "array"
        }
      },
      "required": [
        "id",
        "component"
      ]
    },
    "List": {
      "description": "A list of child components (ids in `children`).",
      "type": "object",
      "properties": {
        "id": {
          "$ref": "#/$defs/ComponentId"
        },
        "component": {
          "const": "List"
        },
        "children": {
          "anyOf": [
            {
              "type": "array",
              "items": {
                "$ref": "#/$defs/ComponentId",
                "description": "The unique identifier for a component."
              },
              "description": "A static list of child component IDs."
            },
            {
              "type": "object",
              "properties": {
                "componentId": {
                  "$ref": "#/$defs/ComponentId",
                  "description": "The unique identifier for a component."
                },
                "path": {
                  "type": "string",
                  "description": "The path to the list of component property objects in the data model."
                }
              },
              "required": [
                "componentId",
                "path"
              ],
              "additionalProperties": false,
              "description": "A template for generating a dynamic list of children."
            }
          ],
          "description": "Defines the children. Use an array of strings for a fixed set of children, or a template object to generate children from a data list."
        },
        "direction": {
          "type": "string",
          "enum": [
            "vertical",
            "horizontal"
          ],
          "default": "vertical",
          "description": "The direction in which the list items are laid out."
        },
        "align": {
          "type": "string",
          "enum": [
            "start",
            "center",
            "end",
            "stretch"
          ],
          "default": "stretch",
          "description": "Defines the alignment of children along the cross axis."
        },
        "listStyle": {
          "type": "string",
          "enum": [
            "ordered",
            "unordered",
            "none"
          ],
          "description": "The style of the list (ordered, unordered, or none)."
        }
      },
      "required": [
        "id",
        "component",
        "children"
      ]
    },
    "Modal": {
      "description": "A dialog: `trigger` is the id of the component that opens it, `content` the id of what it shows. Both must be defined as separate components — a Modal holds ids, never inline children.",
      "type": "object",
      "properties": {
        "id": {
          "$ref": "#/$defs/ComponentId"
        },
        "component": {
          "const": "Modal"
        },
        "trigger": {
          "type": "string",
          "description": "The ID of the component that opens the modal when interacted with (e.g., a button). Do NOT define the component inline."
        },
        "content": {
          "type": "string",
          "description": "The ID of the component to be displayed inside the modal. Do NOT define the component inline."
        }
      },
      "required": [
        "id",
        "component",
        "trigger",
        "content"
      ]
    },
    "NoteEditorCard": {
      "description": "Server-built. Aleph's own code composes this from live project state; do not emit one yourself. Listed here so you can read and reason about a surface you were given.",
      "type": "object",
      "properties": {
        "id": {
          "$ref": "#/$defs/ComponentId"
        },
        "component": {
          "const": "NoteEditorCard"
        },
        "note_id": {
          "$ref": "#/$defs/DynamicString"
        },
        "section_id": {
          "$ref": "#/$defs/DynamicString"
        },
        "title": {
          "$ref": "#/$defs/DynamicString"
        },
        "body_md": {
          "$ref": "#/$defs/DynamicString"
        },
        "edit_action": {
          "$ref": "#/$defs/Action"
        },
        "rename_action": {
          "$ref": "#/$defs/Action"
        },
        "promote_action": {
          "$ref": "#/$defs/Action"
        }
      },
      "required": [
        "id",
        "component"
      ]
    },
    "NotesSurface": {
      "description": "Server-built. Aleph's own code composes this from live project state; do not emit one yourself. Listed here so you can read and reason about a surface you were given.",
      "type": "object",
      "properties": {
        "id": {
          "$ref": "#/$defs/ComponentId"
        },
        "component": {
          "const": "NotesSurface"
        },
        "notes": {
          "$ref": "#/$defs/DynamicValue"
        }
      },
      "required": [
        "id",
        "component"
      ]
    },
    "Row": {
      "description": "A horizontal arrangement of child components (ids in `children`).",
      "type": "object",
      "properties": {
        "id": {
          "$ref": "#/$defs/ComponentId"
        },
        "component": {
          "const": "Row"
        },
        "children": {
          "anyOf": [
            {
              "type": "array",
              "items": {
                "$ref": "#/$defs/ComponentId",
                "description": "The unique identifier for a component."
              },
              "description": "A static list of child component IDs."
            },
            {
              "type": "object",
              "properties": {
                "componentId": {
                  "$ref": "#/$defs/ComponentId",
                  "description": "The unique identifier for a component."
                },
                "path": {
                  "type": "string",
                  "description": "The path to the list of component property objects in the data model."
                }
              },
              "required": [
                "componentId",
                "path"
              ],
              "additionalProperties": false,
              "description": "A template for generating a dynamic list of children."
            }
          ],
          "description": "Defines the children. Use an array of strings for a fixed set of children, or a template object to generate children from a data list. Children cannot be defined inline, they must be referred to by ID."
        },
        "justify": {
          "type": "string",
          "enum": [
            "center",
            "end",
            "spaceAround",
            "spaceBetween",
            "spaceEvenly",
            "start",
            "stretch"
          ],
          "default": "start",
          "description": "Defines the arrangement of children along the main axis (horizontally). Use 'spaceBetween' to push items to the edges, or 'start'/'end'/'center' to pack them together."
        },
        "align": {
          "type": "string",
          "enum": [
            "start",
            "center",
            "end",
            "stretch"
          ],
          "default": "stretch",
          "description": "Defines the alignment of children along the cross axis (vertically). This is similar to the CSS 'align-items' property, but uses camelCase values (e.g., 'start')."
        }
      },
      "required": [
        "id",
        "component",
        "children"
      ]
    },
    "SettingsSurface": {
      "description": "Server-built. Aleph's own code composes this from live project state; do not emit one yourself. Listed here so you can read and reason about a surface you were given.",
      "type": "object",
      "properties": {
        "id": {
          "$ref": "#/$defs/ComponentId"
        },
        "component": {
          "const": "SettingsSurface"
        },
        "title": {
          "$ref": "#/$defs/DynamicValue"
        },
        "sections": {
          "$ref": "#/$defs/DynamicValue"
        },
        "children": {
          "type": "array"
        }
      },
      "required": [
        "id",
        "component"
      ]
    },
    "Slider": {
      "description": "A bounded numeric input. `max` is REQUIRED — without a ceiling there is no track to drag along. Use a TextField with `variant: number` for an unbounded number.",
      "type": "object",
      "properties": {
        "id": {
          "$ref": "#/$defs/ComponentId"
        },
        "component": {
          "const": "Slider"
        },
        "label": {
          "anyOf": [
            {
              "type": "string"
            },
            {
              "$ref": "#/$defs/DataBinding",
              "description": "A JSON Pointer path to a value in the data model."
            },
            {
              "$ref": "#/$defs/FunctionCall"
            }
          ],
          "description": "The label for the slider."
        },
        "min": {
          "type": "number",
          "default": 0,
          "description": "The minimum value of the slider."
        },
        "max": {
          "type": "number",
          "description": "The maximum value of the slider."
        },
        "step": {
          "type": "number",
          "description": "The granularity or step size of the slider."
        },
        "value": {
          "anyOf": [
            {
              "type": "number"
            },
            {
              "$ref": "#/$defs/DataBinding",
              "description": "A JSON Pointer path to a value in the data model."
            },
            {
              "$ref": "#/$defs/FunctionCall"
            }
          ],
          "description": "The current value of the slider."
        },
        "checks": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/CheckRule",
            "description": "A check rule consisting of a condition and an error message."
          },
          "description": "A list of checks to perform."
        }
      },
      "required": [
        "id",
        "component",
        "max",
        "value"
      ]
    },
    "SourceCard": {
      "description": "A reference to an ingested source with its processing status.",
      "type": "object",
      "properties": {
        "id": {
          "$ref": "#/$defs/ComponentId"
        },
        "component": {
          "const": "SourceCard"
        },
        "source_id": {
          "$ref": "#/$defs/DynamicString"
        },
        "short_id": {
          "$ref": "#/$defs/DynamicString"
        },
        "title": {
          "$ref": "#/$defs/DynamicString"
        },
        "url": {
          "$ref": "#/$defs/DynamicString"
        },
        "status": {
          "$ref": "#/$defs/DynamicString"
        },
        "normalized_preview": {
          "$ref": "#/$defs/DynamicString"
        },
        "retracted": {
          "$ref": "#/$defs/DynamicBoolean"
        },
        "open_action": {
          "$ref": "#/$defs/Action"
        },
        "navigate_wiki_action": {
          "$ref": "#/$defs/Action"
        }
      },
      "required": [
        "id",
        "component",
        "source_id",
        "short_id",
        "title",
        "status"
      ]
    },
    "TableCard": {
      "description": "A sortable, filterable data table. Provide `columns` ([{name,label}]) and `rows` (array of objects keyed by column name).",
      "type": "object",
      "properties": {
        "id": {
          "$ref": "#/$defs/ComponentId"
        },
        "component": {
          "const": "TableCard"
        },
        "dataset_version_id": {
          "$ref": "#/$defs/DynamicString"
        },
        "title": {
          "$ref": "#/$defs/DynamicString"
        },
        "columns": {
          "type": "array"
        },
        "rows": {
          "type": "array"
        },
        "_placeholder": {
          "$ref": "#/$defs/DynamicBoolean"
        }
      },
      "required": [
        "id",
        "component"
      ]
    },
    "Tabs": {
      "description": "A tabbed container; each entry in `tabs` names a title and a content id.",
      "type": "object",
      "properties": {
        "id": {
          "$ref": "#/$defs/ComponentId"
        },
        "component": {
          "const": "Tabs"
        },
        "tabs": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "title": {
                "anyOf": [
                  {
                    "type": "string"
                  },
                  {
                    "$ref": "#/$defs/DataBinding",
                    "description": "A JSON Pointer path to a value in the data model."
                  },
                  {
                    "$ref": "#/$defs/FunctionCall"
                  }
                ],
                "description": "The tab title."
              },
              "child": {
                "type": "string",
                "description": "The ID of the child component. Do NOT define the component inline."
              }
            },
            "required": [
              "title",
              "child"
            ],
            "additionalProperties": false
          },
          "minItems": 1,
          "description": "An array of objects, where each object defines a tab with a title and a child component."
        }
      },
      "required": [
        "id",
        "component",
        "tabs"
      ]
    },
    "Text": {
      "description": "A run of text. `text` is the string; `variant` sets heading/body style.",
      "type": "object",
      "properties": {
        "id": {
          "$ref": "#/$defs/ComponentId"
        },
        "component": {
          "const": "Text"
        },
        "text": {
          "anyOf": [
            {
              "type": "string"
            },
            {
              "$ref": "#/$defs/DataBinding",
              "description": "A JSON Pointer path to a value in the data model."
            },
            {
              "$ref": "#/$defs/FunctionCall"
            }
          ],
          "description": "The text content to display. While simple Markdown formatting is supported (i.e. without HTML, images, or links), utilizing dedicated UI components is generally preferred for a richer and more structured presentation."
        },
        "variant": {
          "type": "string",
          "enum": [
            "h1",
            "h2",
            "h3",
            "h4",
            "h5",
            "caption",
            "body"
          ],
          "default": "body",
          "description": "A hint for the base text style."
        }
      },
      "required": [
        "id",
        "component",
        "text"
      ]
    },
    "TextField": {
      "description": "A text input with a `label`. `variant` picks the kind: `shortText`, `longText` (multi-line), `number`, or `obscured` (a secret — note that anything typed here travels in the action context and is recorded, so never ask for a credential this way). `value` binds to the data model.",
      "type": "object",
      "properties": {
        "id": {
          "$ref": "#/$defs/ComponentId"
        },
        "component": {
          "const": "TextField"
        },
        "label": {
          "anyOf": [
            {
              "type": "string"
            },
            {
              "$ref": "#/$defs/DataBinding",
              "description": "A JSON Pointer path to a value in the data model."
            },
            {
              "$ref": "#/$defs/FunctionCall"
            }
          ],
          "description": "The text label for the input field."
        },
        "value": {
          "anyOf": [
            {
              "type": "string"
            },
            {
              "$ref": "#/$defs/DataBinding",
              "description": "A JSON Pointer path to a value in the data model."
            },
            {
              "$ref": "#/$defs/FunctionCall"
            }
          ],
          "description": "The value of the text field."
        },
        "variant": {
          "type": "string",
          "enum": [
            "longText",
            "number",
            "shortText",
            "obscured"
          ],
          "default": "shortText",
          "description": "The type of input field to display."
        },
        "validationRegexp": {
          "type": "string",
          "description": "A regular expression used for client-side validation of the input."
        },
        "checks": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/CheckRule",
            "description": "A check rule consisting of a condition and an error message."
          },
          "description": "A list of checks to perform."
        }
      },
      "required": [
        "id",
        "component",
        "label"
      ]
    },
    "Video": {
      "description": "A video player for a `url`.",
      "type": "object",
      "properties": {
        "id": {
          "$ref": "#/$defs/ComponentId"
        },
        "component": {
          "const": "Video"
        },
        "url": {
          "anyOf": [
            {
              "type": "string"
            },
            {
              "$ref": "#/$defs/DataBinding",
              "description": "A JSON Pointer path to a value in the data model."
            },
            {
              "$ref": "#/$defs/FunctionCall"
            }
          ],
          "description": "The URL of the video to display."
        }
      },
      "required": [
        "id",
        "component",
        "url"
      ]
    },
    "WikiPageCard": {
      "description": "Server-built. Aleph's own code composes this from live project state; do not emit one yourself. Listed here so you can read and reason about a surface you were given.",
      "type": "object",
      "properties": {
        "id": {
          "$ref": "#/$defs/ComponentId"
        },
        "component": {
          "const": "WikiPageCard"
        },
        "page_id": {
          "$ref": "#/$defs/DynamicString"
        },
        "body_md": {
          "$ref": "#/$defs/DynamicString"
        },
        "claims": {
          "type": "array"
        },
        "citations": {
          "type": "array"
        },
        "wikilinks_out": {
          "type": "array"
        },
        "page_meta": {},
        "html_url": {
          "$ref": "#/$defs/DynamicString"
        },
        "retracted": {
          "$ref": "#/$defs/DynamicBoolean"
        },
        "derived": {
          "$ref": "#/$defs/DynamicBoolean"
        },
        "read_only": {
          "$ref": "#/$defs/DynamicBoolean"
        },
        "navigate_wiki_action": {
          "$ref": "#/$defs/Action"
        },
        "approve_action": {
          "$ref": "#/$defs/Action"
        },
        "reject_action": {
          "$ref": "#/$defs/Action"
        },
        "repair_links_action": {
          "$ref": "#/$defs/Action"
        }
      },
      "required": [
        "id",
        "component"
      ]
    },
    "WikiSurface": {
      "description": "Server-built. Aleph's own code composes this from live project state; do not emit one yourself. Listed here so you can read and reason about a surface you were given.",
      "type": "object",
      "properties": {
        "id": {
          "$ref": "#/$defs/ComponentId"
        },
        "component": {
          "const": "WikiSurface"
        },
        "pages": {
          "$ref": "#/$defs/DynamicValue"
        },
        "open": {
          "$ref": "#/$defs/DynamicValue"
        },
        "categories": {
          "$ref": "#/$defs/DynamicValue"
        },
        "health": {
          "$ref": "#/$defs/DynamicValue"
        }
      },
      "required": [
        "id",
        "component"
      ]
    }
  }
} as const;
