import { chromium } from "@playwright/test";
const b = await chromium.launch();
const p = await b.newPage();
const errs = [], reqs = [], pageErrs = [];
p.on("console", m => { if (["error","warning"].includes(m.type())) errs.push(`[${m.type()}] ${m.text()}`); });
p.on("pageerror", e => pageErrs.push(String(e)));
p.on("requestfailed", r => reqs.push(`FAILED ${r.method()} ${r.url()} :: ${r.failure()?.errorText}`));
p.on("response", r => { if (r.status() >= 400) reqs.push(`HTTP ${r.status()} ${r.request().method()} ${r.url()}`); });
await p.goto(process.argv[2], { waitUntil: "networkidle", timeout: 60000 }).catch(e => pageErrs.push("GOTO: "+e.message));
await p.waitForTimeout(6000);
console.log("=== PAGE ERRORS ==="); pageErrs.forEach(e=>console.log("  "+e));
console.log("=== CONSOLE ==="); [...new Set(errs)].slice(0,25).forEach(e=>console.log("  "+e));
console.log("=== NETWORK FAILURES ==="); [...new Set(reqs)].slice(0,25).forEach(e=>console.log("  "+e));
console.log("=== VISIBLE TEXT (first 600) ===");
console.log((await p.innerText("body").catch(()=> "<no body>")).slice(0,600));
await b.close();
