import { chromium } from "@playwright/test";
const b = await chromium.launch();
const p = await b.newPage();
const errs = [], reqs = [];
p.on("console", m => { if (m.type()==="error") errs.push(`[error] ${m.text()}`.slice(0,220)); });
p.on("response", r => { if (r.status() >= 400) reqs.push(`HTTP ${r.status()} ${r.request().method()} ${r.url()}`); });
await p.goto("http://192.168.1.158:5173/", { waitUntil: "networkidle", timeout: 60000 });
await p.getByText("vllm-smoke").first().click().catch(()=>{});
await p.waitForTimeout(6000);
const box = p.getByRole("textbox").first();
await box.fill("What are sharp-wave ripples? Answer in one sentence.").catch(()=>{});
await box.press("Enter").catch(()=>{});
await p.waitForTimeout(75000);
const body = await p.innerText("body").catch(()=>"");
console.log("=== CONSOLE ERRORS ==="); [...new Set(errs)].slice(0,10).forEach(e=>console.log("  "+e));
console.log("=== HTTP >=400 ==="); [...new Set(reqs)].filter(r=>!r.includes("/stream")).slice(0,10).forEach(e=>console.log("  "+e));
console.log("=== ripple mentioned in page? ===", /ripple/i.test(body));
const i = body.search(/sharp-wave|ripple/i);
console.log("=== EXCERPT ===\n" + (i>=0 ? body.slice(Math.max(0,i-200), i+500) : body.slice(-700)));
await b.close();
