import { chromium } from "@playwright/test";
const b = await chromium.launch();
const p = await b.newPage();
const errs = [];
p.on("console", m => { if (m.type()==="error") errs.push(m.text().slice(0,200)); });
await p.goto("http://192.168.1.158:5173/", { waitUntil: "networkidle", timeout: 60000 });
await p.getByText("chat-check").first().click().catch(e=>console.log("click:",e.message));
await p.waitForTimeout(7000);
const before = await p.innerText("body");
const box = p.getByRole("textbox").first();
await box.fill("Say exactly: PONG");
await box.press("Enter");
await p.waitForTimeout(90000);
const after = await p.innerText("body");
const added = after.replace(before, "");
console.log("=== CONSOLE ERRORS ==="); [...new Set(errs)].slice(0,8).forEach(e=>console.log("  "+e));
console.log("=== NEW CONTENT AFTER SENDING ===");
console.log(added.slice(0,900));
await b.close();
