import { chromium } from '@playwright/test';
const browser = await chromium.launch();
const page = await browser.newPage();
const errs = [];
page.on('pageerror', e => errs.push(String(e).slice(0,200)));
await page.goto('http://localhost:5173/', { waitUntil: 'networkidle' });
await page.getByText('Neurosymbolic AI & LLM reasoning').first().click();
await page.waitForTimeout(2500);
await page.getByText('Topic pages', { exact: false }).first().click().catch(()=>{});
await page.waitForTimeout(1200);
const item = page.getByText('Ablation Study', { exact: false }).first();
console.log('page entry found:', await item.count());
await item.click();
await page.waitForTimeout(3000);
const txt = (await page.textContent('body')||'').replace(/\s+/g,' ');
const idx = txt.indexOf('Ablation Study');
console.log('--- content around the opened page ---');
console.log(txt.slice(idx, idx + 500));
console.log('ERRORS:', errs.length ? errs.join(' | ') : '(none)');
await page.screenshot({ path: '/tmp/aleph-run/wiki-open.png', fullPage: true });
await browser.close();
