// GENERATED by scripts/gen_catalog.py from catalog.json — do not edit.
// Mirror of `packages/aleph-a2ui/src/aleph_a2ui/catalog.json`. The web app
// fetches the canonical schema from `GET /v1/a2ui/catalog` at startup and
// validates against it; the static lists below are the *type* contract, which
// is what makes a missing renderer a compile error instead of an empty pane.

export const CATALOG_VERSION = "1.0.0";

export const COMPONENT_NAMES = [
  "ApprovalCard",
  "ArtifactCard",
  "ArtifactsSurface",
  "BriefsSurface",
  "ChartCard",
  "ClaimCard",
  "DiffCard",
  "FindingCard",
  "FormCard",
  "GroundingSurface",
  "HtmlDocCard",
  "HtmlFrameCard",
  "ImageCard",
  "NoteEditorCard",
  "NotesSurface",
  "SourceCard",
  "TableCard",
  "WikiPageCard",
  "WikiSurface",
  "InspectorSurface",
  "SettingsSurface",
] as const;

export type ComponentName = (typeof COMPONENT_NAMES)[number];

export const ACTION_NAMES = [
  "approve",
  "compose_dossier",
  "create_note",
  "edit_note",
  "feedback",
  "focus_tab",
  "highlight_claim",
  "navigate_wiki",
  "open",
  "plugin.settings.save",
  "promote_note",
  "reject",
  "rename_note",
  "repair_links",
  "spotlight",
  "submit_form",
  "unpin",
] as const;

export type ActionName = (typeof ACTION_NAMES)[number];

/**
 * The wire shape of a rendered component. Mirrors the `_comp()` envelope every
 * catalog entry shares — `type`/`id`/`props` required, `data_bindings` and
 * `children` optional — so a renderer destructuring a payload is typed against
 * the same contract the Python validator enforces.
 */
export interface A2UIComponent {
  type: ComponentName;
  id: string;
  props: Record<string, unknown>;
  data_bindings?: Record<string, unknown>;
  children?: A2UIComponent[];
}
