"""API routes."""

from aleph_api.routes import (
    agent_tokens,
    aiq_internal,
    aliases,
    assistant,
    briefs,
    cards,
    chunks,
    connector_credentials,
    connectors,
    cost,
    feedback,
    handedits,
    health,
    ledger,
    me,
    model_profile,
    notes,
    projects,
    smoketest,
    sources,
    surfaces,
    synthesize,
    wiki,
)

__all__ = [
    "agent_tokens",
    "aiq_internal",
    "aliases",
    "assistant",
    "briefs",
    "cards",
    "chunks",
    "connector_credentials",
    "connectors",
    "cost",
    "feedback",
    "handedits",
    "health",
    "ledger",
    "me",
    "model_profile",
    "notes",
    "projects",
    "smoketest",
    "sources",
    "surfaces",
    "synthesize",
    "wiki",
]
