"""Vault exporter — the wiki as markdown files somebody else can read.

Three places in the tree said an Aleph project "opens as an Obsidian vault" and
nothing anywhere wrote one. This module is that claim made true, and it is what
makes the knowledge layer leaveable: a user can take the corpus somewhere else,
which is the only version of "your data is yours" that is not a promise.

**Two dialects, one bundle shape.** The files, the frontmatter and the ordering
are identical in both; the *link syntax* differs, and so does what happens to a
link whose target is not in the bundle — see ``DanglingLink``, which is the only
other difference and follows from the syntax.

- ``obsidian`` emits ``[[slug|Display]]``. Obsidian resolves those; nothing else
  does.
- ``okf`` emits ``[Display](./slug.md)`` — a standard markdown link, which is
  what Google's Open Knowledge Format v0.1 requires between concept documents,
  and what every other markdown reader already understands.

The okf bundle also declares ``okf_version: "0.1"`` in ``index.md``. The
obsidian bundle does **not**, and that omission is deliberate: an obsidian
bundle uses wikilinks, so it is not a conforming OKF bundle, and stamping a
conformance marker on it would be exactly the kind of false claim this
workstream exists to delete.

**Nothing here touches the ORM.** The exporter takes ``VaultPage`` — a flat view
model — because the wiki's storage is expected to move (docs/decisions.md D1,
the Claim Spine), and a format module that imports ``WikiPage`` has to be
rewritten when it does. The caller does the query; this module owns the format.

**Determinism is a feature, not tidiness.** Filenames are sorted, zip entry
timestamps are pinned to the DOS epoch, and every derived string (the index
summaries, the link display text) is computed from the *rendered* bytes rather
than from anything the caller held on to. That is what makes
``render_vault(parse_vault(render_vault(x)))`` byte-identical to
``render_vault(x)``, which is the only way to know the format loses nothing: a
dropped field shows up as a diff instead of as silence.
"""

from __future__ import annotations

import io
import re
import zipfile
from collections.abc import Callable, Iterable, Mapping, Sequence
from dataclasses import dataclass, field
from datetime import date

from aleph_wiki.frontmatter import Frontmatter, parse, render, strip

__all__ = [
    "DEFAULT_PAGE_TYPE",
    "DIALECTS",
    "INDEX_FILENAME",
    "OKF_VERSION",
    "RESERVED_STEMS",
    "DanglingLink",
    "VaultExport",
    "VaultPage",
    "parse_vault",
    "render_vault",
    "vault_bytes",
]

#: The two link dialects. One flag, because they are the same bundle written two
#: ways — split into two exporters and one of them ends up a feature behind.
DIALECTS: tuple[str, ...] = ("obsidian", "okf")

#: Open Knowledge Format version the `okf` dialect claims. Declared in
#: `index.md` only; concepts carry no version marker (OKF v0.1 puts it on the
#: root index).
OKF_VERSION = "0.1"

INDEX_FILENAME = "index.md"

#: OKF reserves `index.md` (directory listing) and `log.md` (update history) as
#: scaffolding, not concepts. A page whose slug is `index` would otherwise
#: overwrite the vault's own directory listing and take every page's navigation
#: with it, silently — the zip would just have one fewer file.
RESERVED_STEMS = frozenset({"index", "log"})

#: OKF v0.1 requires a non-empty `type` on every concept. 40 of the 65 live
#: non-stub pages have `page_type` NULL, so with no fallback the export is 62%
#: non-conforming. `concept` is the neutral choice, and it is the *export's*
#: assertion — nothing here decides that an untyped page is a concept for any
#: other purpose, and no row is written.
DEFAULT_PAGE_TYPE = "concept"

#: `[[target]]`, `[[target|display]]`, `[[target#anchor]]` and combinations.
#: Same shape as `aleph_wiki.frontmatter._WIKILINK`, but capturing the anchor
#: and the display rather than discarding them — extraction did not need them,
#: rendering does.
_WIKILINK = re.compile(
    r"\[\[(?P<target>[^\]\[|#]+)(?:#(?P<anchor>[^\]\[|]*))?(?:\|(?P<display>[^\]\[]*))?\]\]"
)

#: The okf dialect's own output, read back. Anchored on the `./` prefix so an
#: external URL or an absolute path is left alone — only intra-vault concept
#: links are de-sugared back to wikilinks on import.
_OKF_LINK = re.compile(
    r"\[(?P<display>[^\]\[]*)\]\(\./(?P<stem>[A-Za-z0-9._-]+)\.md(?:#(?P<anchor>[^)\s]*))?\)"
)

#: Anything outside this set is replaced when a slug becomes a filename. Slugs
#: are generated by `aleph_wiki.links.slugify_link` and are already safe, but a
#: hand-written or legacy slug containing `/` or `..` would write outside the
#: extraction directory, and a zip that can escape its own directory is not a
#: format problem, it is a vulnerability.
_UNSAFE_IN_NAME = re.compile(r"[^a-z0-9._-]+")

#: A fenced code block, opening or closing. Residual `[[` is left alone inside
#: one: a fence shows raw text, so escaping there would put visible backslashes
#: into somebody's code sample.
_FENCE_LINE = re.compile(r"^\s*(```|~~~)")

_ZIP_EPOCH = (1980, 1, 1, 0, 0, 0)


@dataclass(frozen=True, slots=True)
class VaultPage:
    """One page, flattened away from whatever currently stores it.

    `body_md` is the canonical wikilink form — what the database holds — with or
    without its own frontmatter block. The frontmatter written to the file is
    rebuilt from these fields and never copied from the body: the columns are
    what the system filters and lints on, so on a disagreement the columns win.
    That is the same drift `aleph_wiki.lint` reports as `frontmatter-drift`,
    resolved here rather than exported.
    """

    title: str
    slug: str
    body_md: str = ""
    page_type: str | None = None
    category: str | None = None
    tags: tuple[str, ...] = ()
    related: tuple[str, ...] = ()
    sources: tuple[str, ...] = ()
    aliases: tuple[str, ...] = ()
    confidence: str | None = None
    contested: bool = False
    contradictions: tuple[str, ...] = ()
    created: date | None = None
    updated: date | None = None


@dataclass(frozen=True, slots=True)
class DanglingLink:
    """A link whose target is not a file in the bundle.

    Reported in both dialects; *emitted* in only one, and that asymmetry is the
    one place the dialects differ beyond syntax:

    * ``okf`` writes the display text with no link. `[Ghost](./ghost.md)` would
      point at a file that is not in the zip — it looks like navigation and
      leads nowhere, and a markdown reader has no way to say so.
    * ``obsidian`` keeps ``[[Ghost]]``. A wikilink to a note that does not exist
      is not broken in Obsidian, it is a **red link** — the writing queue, the
      graph view's frontier, and exactly how `docs/wiki-schema.md` models the
      `stub` status. Dropping it would delete the queue: 945 of the 1,025 links
      in the live corpus point at stub pages, which the export excludes because
      92% of that corpus is stubs.

    Either way the count is on the export, so a caller learns that 945 links
    lead outside the bundle rather than discovering it in a reader.
    """

    from_slug: str
    from_title: str
    target: str
    display: str


@dataclass(frozen=True, slots=True)
class VaultExport:
    dialect: str
    files: Mapping[str, str]
    dangling: tuple[DanglingLink, ...] = ()

    @property
    def page_count(self) -> int:
        """Concept files, excluding the reserved scaffolding."""
        return sum(1 for name in self.files if name.rsplit(".", 1)[0] not in RESERVED_STEMS)

    def to_bytes(self) -> bytes:
        """The bundle as a zip.

        Entry order is sorted and every timestamp is pinned, so two exports of
        the same corpus are byte-identical. Without that, a `diff` between two
        exports reports every file as changed and the round-trip check proves
        nothing.
        """
        buf = io.BytesIO()
        with zipfile.ZipFile(buf, "w", zipfile.ZIP_DEFLATED) as zf:
            for name in sorted(self.files):
                info = zipfile.ZipInfo(name, date_time=_ZIP_EPOCH)
                info.compress_type = zipfile.ZIP_DEFLATED
                info.external_attr = 0o644 << 16
                zf.writestr(info, self.files[name])
        return buf.getvalue()


@dataclass(slots=True)
class _Resolver:
    """Link target → file stem, by the wiki's own three resolution rules.

    Exact title, then case-insensitive title, then slug — the order
    `aleph_wiki.links.resolve_broken_links` uses and `docs/wiki-schema.md`
    documents. Repeating the order rather than approximating it is the point: a
    resolver that differs from the repair's resolver calls links broken that
    repairing would have fixed, which is the defect that left `[[Source:S0002]]`
    red forever on the live corpus.
    """

    by_title: dict[str, str] = field(default_factory=dict)
    by_title_ci: dict[str, str] = field(default_factory=dict)
    by_stem: dict[str, str] = field(default_factory=dict)

    def add(self, *, title: str, slug: str, stem: str) -> None:
        self.by_title.setdefault(title, stem)
        self.by_title_ci.setdefault(title.lower(), stem)
        self.by_stem.setdefault(slug.strip().lower(), stem)
        self.by_stem.setdefault(stem, stem)

    def resolve(self, target: str) -> str | None:
        probe = target.strip()
        if probe in self.by_title:
            return self.by_title[probe]
        lowered = probe.lower()
        if lowered in self.by_title_ci:
            return self.by_title_ci[lowered]
        if lowered in self.by_stem:
            return self.by_stem[lowered]
        return self.by_stem.get(_slugify(probe))


def _slugify(text: str) -> str:
    """`Source:S0002` → `source-s0002`.

    Deliberately re-stated rather than imported from `aleph_wiki.links`: this
    module is the format, and the format must not stop working because the
    wiki's storage layer moved. Same rule, one line, no dependency on a package
    that is scheduled to change shape.
    """
    return _UNSAFE_IN_NAME.sub("-", text.strip().lower()).strip("-")


def _plain(text: str) -> str:
    """Link markup flattened to the words a reader sees.

    Used only for the index summaries. Both dialects flatten to the same string,
    so the index reads the same either way, and — the reason it exists — the
    summary is then stable across an export/import/export cycle, where the
    wikilink form of a link is not (`[[Attention]]` comes back as
    `[[attention|Attention]]`, which is the same link and different bytes).
    """
    flat = _OKF_LINK.sub(lambda m: m.group("display") or m.group("stem"), text)
    return _WIKILINK.sub(lambda m: (m.group("display") or m.group("target") or "").strip(), flat)


def _first_sentence(body: str, limit: int = 140) -> str:
    """A one-line summary lifted from the body.

    Derived rather than passed in, so `index.md` is reproducible from the
    concept files alone. A summary the caller supplied would survive an export
    and vanish on import, and the round-trip would then report a diff for a
    field the format never carried.
    """
    for raw in _plain(body).splitlines():
        line = raw.strip()
        if not line or line.startswith(("#", ">", "|", "-", "*", "!", "```")):
            continue
        line = line.replace("**", "").replace("__", "")
        sentence = line.split(". ")[0].rstrip(".")
        return sentence[:limit] + ("…" if len(sentence) > limit else "")
    return ""


def _clean(values: Iterable[str]) -> list[str]:
    """Strip and drop empties.

    `frontmatter.parse` strips on read, so an export that writes `" tag "`
    re-exports as `"tag"` and the round-trip reports a diff for a difference
    nobody made. Normalising on write closes that.
    """
    return [v.strip() for v in values if v.strip()]


def _filenames(pages: Sequence[VaultPage]) -> dict[str, str]:
    """slug → filename, collision-free and safe to extract.

    Two distinct slugs can normalise to the same filename, and a slug can be
    `index`. Either one silently drops a page from the bundle — the zip is one
    file shorter and nothing says so — so both are resolved by suffixing.
    """
    out: dict[str, str] = {}
    taken: set[str] = {f"{stem}.md" for stem in RESERVED_STEMS}
    for page in sorted(pages, key=lambda p: (p.slug, p.title)):
        stem = _UNSAFE_IN_NAME.sub("-", page.slug.strip().lower()).strip("-.") or "untitled"
        if stem in RESERVED_STEMS:
            stem = f"{stem}-concept"
        candidate = f"{stem}.md"
        n = 2
        while candidate in taken:
            candidate = f"{stem}-{n}.md"
            n += 1
        taken.add(candidate)
        out[page.slug] = candidate
    return out


def _escape_display(display: str) -> str:
    """Escape brackets in a link's visible text.

    A page titled `[e2e] theme diff project` rendered as
    `[[e2e] theme diff project](./slug.md)`. That is not an Obsidian wikilink —
    it is a markdown link whose label opens with `[` — but every reader that
    scans for `[[` sees one, including this repo's own "no Obsidian syntax in
    the okf dialect" check, and a markdown parser closes the label at the FIRST
    `]`, so the rendered link text becomes `[e2e` and the rest leaks into the
    page as prose.

    Titles are free text. Nothing stops a page being called `Attention [2017]`
    or `The [[wikilink]] problem`, and both are reasonable titles.
    """
    return display.replace("\\", "\\\\").replace("[", "\\[").replace("]", "\\]")


def _link(*, stem: str, display: str, anchor: str, dialect: str) -> str:
    if dialect == "okf":
        safe = _escape_display(display)
        return f"[{safe}](./{stem}.md" + (f"#{anchor})" if anchor else ")")
    inner = f"{stem}#{anchor}" if anchor else stem
    # `[[attention]]` reads as "attention" in Obsidian, so the author's
    # capitalisation is kept as an explicit display whenever it differs from the
    # stem. Dropping it would quietly lowercase the prose.
    return f"[[{inner}]]" if display == stem and not anchor else f"[[{inner}|{display}]]"


def _render_links(
    body: str, *, page: VaultPage, dialect: str, resolver: _Resolver
) -> tuple[str, list[DanglingLink]]:
    """Rewrite every `[[wikilink]]` into the requested dialect.

    An unresolvable target is always reported (see `DanglingLink`). In `okf` it
    is written as plain display text, because a markdown link into a file that
    is not in the bundle fails in the reader rather than in the exporter, which
    is strictly worse — the exporter knows, and the reader can only guess. In
    `obsidian` it is kept as a wikilink, because a wikilink to a note that does
    not exist is a red link, which is a state Obsidian has and a reader
    understands.
    """
    dangling: list[DanglingLink] = []

    def _one(match: re.Match[str]) -> str:
        target = (match.group("target") or "").strip()
        anchor = (match.group("anchor") or "").strip()
        raw_display = match.group("display")
        display = raw_display.strip() if raw_display is not None else target
        stem = resolver.resolve(target)
        if stem is None:
            dangling.append(
                DanglingLink(
                    from_slug=page.slug,
                    from_title=page.title,
                    target=target,
                    display=display,
                )
            )
            if dialect == "okf":
                return display
            return _link(stem=target, display=display, anchor=anchor, dialect=dialect)
        return _link(
            stem=stem[: -len(".md")] if stem.endswith(".md") else stem,
            display=display,
            anchor=anchor,
            dialect=dialect,
        )

    rewritten = _sub_outside_fences(_WIKILINK, _one, body)
    return (_escape_residual_brackets(rewritten) if dialect == "okf" else rewritten), dangling


def _sub_outside_fences(
    pattern: re.Pattern[str], repl: Callable[[re.Match[str]], str], body: str
) -> str:
    """Apply `pattern.sub` line by line, skipping fenced code blocks.

    A wiki page that documents wikilink syntax contains wikilinks it does not
    mean — inside a fence, `[[Attention]]` is an example of the syntax, not a
    link to a page. Rewriting it to `[Attention](./attention.md)` silently edits
    somebody's example into something that is no longer the thing being shown,
    and on the OKF side it also invents a dangling-link report for a link that
    was never a link.

    `_escape_residual_brackets` already skipped fences for the same reason. The
    rewrite did not, which meant the two halves of the same rule disagreed.
    """
    out: list[str] = []
    in_fence = False
    for line in body.splitlines(keepends=True):
        if _FENCE_LINE.match(line):
            in_fence = not in_fence
            out.append(line)
            continue
        out.append(line if in_fence else pattern.sub(repl, line))
    return "".join(out)


def _escape_residual_brackets(body: str) -> str:
    """Escape any `[[` the wikilink pattern could not match.

    Not hypothetical. Two hub pages on the live corpus carry a summary that
    `aleph_wiki.navigation` truncated at 140 characters *mid-wikilink*, leaving
    an unclosed `[[A…` in the stored body. `_WIKILINK` cannot match it, so it
    would survive into an OKF bundle as syntax an OKF reader would try to
    interpret. `\\[\\[` renders as a literal `[[` for a human and is not a link
    for anything else, so the words are unchanged and the syntax is gone.

    Inside a fenced code block it is left alone: a fence shows raw text, and a
    backslash added there is a visible edit to somebody's code. `check-okf.py`
    still reports what survives, which is the correct outcome — a `[[` in a
    code fence is ambiguous to an OKF consumer too, and a person should look.
    """
    out: list[str] = []
    in_fence = False
    for line in body.splitlines(keepends=True):
        if _FENCE_LINE.match(line):
            in_fence = not in_fence
            out.append(line)
            continue
        out.append(line if in_fence else line.replace("[[", "\\[\\["))
    return "".join(out)


def _frontmatter(page: VaultPage) -> Frontmatter:
    return Frontmatter(
        title=page.title.strip(),
        aliases=_clean(page.aliases),
        created=page.created,
        updated=page.updated,
        type=(page.page_type or DEFAULT_PAGE_TYPE).strip() or DEFAULT_PAGE_TYPE,
        category=(page.category or "").strip() or None,
        tags=_clean(page.tags),
        related=_clean(page.related),
        sources=_clean(page.sources),
        confidence=(page.confidence or "").strip() or None,
        contested=page.contested,
        contradictions=_clean(page.contradictions),
    )


def _render_index(
    pages: Sequence[VaultPage],
    *,
    dialect: str,
    project_title: str,
    filenames: Mapping[str, str],
    summaries: Mapping[str, str],
) -> str:
    """The vault's directory listing.

    Reserved scaffolding under OKF, not a concept: no `type`, and in the okf
    dialect the `okf_version` marker that identifies the bundle. Sectioned by
    category with an uncategorised tail, for the same reason
    `aleph_wiki.navigation.build_index` has one — a page with no category is
    otherwise present in the vault and absent from the one file that claims to
    list everything.
    """
    by_category: dict[str, list[VaultPage]] = {}
    for page in pages:
        by_category.setdefault((page.category or "").strip(), []).append(page)

    lines: list[str] = []
    if dialect == "okf":
        lines += ["---", f'okf_version: "{OKF_VERSION}"', "---", ""]
    lines += [f"# {project_title}", "", f"{len(pages)} pages.", ""]

    # Uncategorised last: it is a gap to close, not a section to read first.
    for category in sorted(by_category, key=lambda c: (c == "", c)):
        lines += [f"## {category or 'Uncategorised'}", ""]
        for page in sorted(by_category[category], key=lambda p: (p.title.lower(), p.slug)):
            stem = filenames[page.slug][: -len(".md")]
            entry = _link(stem=stem, display=page.title, anchor="", dialect=dialect)
            summary = summaries.get(page.slug, "")
            lines.append(f"- {entry}" + (f" — {summary}" if summary else ""))
        lines.append("")
    return "\n".join(lines).rstrip("\n") + "\n"


def render_vault(
    pages: Iterable[VaultPage],
    *,
    dialect: str = "obsidian",
    project_title: str = "Wiki",
) -> VaultExport:
    """One markdown file per page, plus `index.md`, in the requested dialect.

    Stubs are the caller's business: a stub has no body, and a file whose only
    content is frontmatter is not a concept in any format. The caller filters;
    this function exports what it is handed.
    """
    if dialect not in DIALECTS:
        msg = f"unknown vault dialect {dialect!r}; expected one of {', '.join(DIALECTS)}"
        raise ValueError(msg)

    ordered = sorted(pages, key=lambda p: (p.slug, p.title))
    filenames = _filenames(ordered)

    resolver = _Resolver()
    for page in ordered:
        stem = filenames[page.slug]
        resolver.add(title=page.title.strip(), slug=page.slug, stem=stem[: -len(".md")])

    files: dict[str, str] = {}
    dangling: list[DanglingLink] = []
    summaries: dict[str, str] = {}
    for page in ordered:
        rendered, page_dangling = _render_links(
            strip(page.body_md), page=page, dialect=dialect, resolver=resolver
        )
        dangling.extend(page_dangling)
        # Summarised from the RENDERED body, not the stored one: that is what
        # survives a round trip unchanged.
        summaries[page.slug] = _first_sentence(rendered)
        files[filenames[page.slug]] = render(_frontmatter(page), rendered)

    files[INDEX_FILENAME] = _render_index(
        ordered,
        dialect=dialect,
        project_title=project_title,
        filenames=filenames,
        summaries=summaries,
    )
    return VaultExport(dialect=dialect, files=files, dangling=tuple(dangling))


def vault_bytes(
    pages: Iterable[VaultPage],
    *,
    dialect: str = "obsidian",
    project_title: str = "Wiki",
) -> bytes:
    """Render and zip in one call."""
    return render_vault(pages, dialect=dialect, project_title=project_title).to_bytes()


def parse_vault(files: Mapping[str, str]) -> list[VaultPage]:
    """Read a bundle back into `VaultPage`s — the import half of the round trip.

    This is a **format** importer, not a database importer. It exists to prove
    the export is lossless, by making
    `render_vault(parse_vault(render_vault(x)))` produce identical bytes.
    Nothing here writes a revision, a ledger event or a row; anything that
    reaches the wiki has to go through `WikiService`, and that path does not
    exist yet.

    The dialect is detected from `index.md`: markdown links are de-sugared back
    to wikilinks only in an okf bundle, because in an obsidian bundle a
    `[text](./x.md)` link is an ordinary markdown link somebody wrote on purpose
    and rewriting it would be an edit, not a read.
    """
    index = files.get(INDEX_FILENAME, "")
    is_okf = f'okf_version: "{OKF_VERSION}"' in index or f"okf_version: '{OKF_VERSION}'" in index

    out: list[VaultPage] = []
    for name in sorted(files):
        if not name.endswith(".md"):
            continue
        stem = name[: -len(".md")]
        if stem in RESERVED_STEMS:
            continue
        fm, body = parse(files[name])
        if is_okf:
            body = _OKF_LINK.sub(_to_wikilink, body)
        out.append(
            VaultPage(
                title=fm.title or stem,
                slug=stem,
                body_md=body,
                page_type=fm.type,
                category=fm.category,
                tags=tuple(fm.tags),
                related=tuple(fm.related),
                sources=tuple(fm.sources),
                aliases=tuple(fm.aliases),
                confidence=fm.confidence,
                contested=fm.contested,
                contradictions=tuple(fm.contradictions),
                created=fm.created,
                updated=fm.updated,
            )
        )
    return out


def _to_wikilink(match: re.Match[str]) -> str:
    stem = match.group("stem")
    anchor = match.group("anchor") or ""
    display = match.group("display") or stem
    target = f"{stem}#{anchor}" if anchor else stem
    return f"[[{target}]]" if display == stem and not anchor else f"[[{target}|{display}]]"
