#!/usr/bin/env python3
"""Generate every catalog copy. Two inputs, neither of them a transcription.

The A2UI catalog was maintained by hand in three places: a 614-line
`catalog.py`, a 65-line `catalog.ts`, and a ~265-line object literal inside
`copilot-runtime/src/server.ts`. Nothing tied them together, and they drifted
in ways that were invisible until an agent hit them:

* `ClaimCard.confidence` contained **no** `"cited"` in any copy — the value both
  wiki writers hardcode, so validating a real card would have rejected it;
* the agent-facing copy offered `"initial"`, which nothing recognises, and
  omitted `"retracted"`, making the WP-6 state unemittable;
* `"dismiss"` was declared dispatchable with no handler behind it.

Those were found and fixed, and `tests/unit/test_catalog_agreement.py` now
catches a *recurrence*. But catching drift is a weaker guarantee than not being
able to drift: this generator makes `catalog.json` the only file a human edits,
and `check-catalog-generated.sh` fails the build if a generated file no longer
matches it.

That fixed three copies of Aleph's OWN cards and left a fourth disagreement
standing, because it was not a copy at all — it was a subset. The agent-facing
catalog was assembled here by FILTERING `catalog.json` to the ten entries
carrying an `agent` block plus nine hand-listed primitives, while the browser
rendered thirty-nine components. The twenty it never mentioned included every
input control, so a form was unaskable and a plugin settings screen was
undeclarable, and no gate could see it: `catalog.json` was internally
consistent, and the renderer was never consulted. So there are now two inputs:

* `catalog.json` — the only file a human edits. Aleph's own card schemas (what
  the server validates), the action vocabulary, and the PROSE: which components
  the agent is invited to emit, and what each one is for.
* `render_catalog.generated.json` — the component set and the prop schemas,
  extracted from the renderer's live zod catalog by
  `packages/aleph-a2ui/tools/extract_render_catalog.mjs`. Committed rather than
  re-extracted here, so this script and `check-catalog-generated.sh` need no JS
  toolchain; its freshness is a separate gate,
  `scripts/check-agent-catalog-covers-renderer.sh`.

Run:  python scripts/gen_catalog.py [--check]

`--check` regenerates into memory and diffs, changing nothing — the CI mode.
"""

from __future__ import annotations

import argparse
import json
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parents[1]
CANONICAL = ROOT / "packages/aleph-a2ui/src/aleph_a2ui/catalog.json"
RENDER_CATALOG = ROOT / "packages/aleph-a2ui/src/aleph_a2ui/render_catalog.generated.json"
WEB_CATALOG = ROOT / "apps/web/src/a2ui/catalog.ts"
RUNTIME_CATALOG = ROOT / "apps/copilot-runtime/src/catalog.generated.ts"

BANNER = "// GENERATED by scripts/gen_catalog.py from catalog.json — do not edit."
RUNTIME_BANNER = (
    "// GENERATED by scripts/gen_catalog.py from catalog.json"
    " + render_catalog.generated.json — do not edit."
)

#: Prefixed to a component the renderer can draw but that no `agent` block in
#: `catalog.json` invites the agent to emit. It used to be omitted from the
#: agent catalog entirely, on the reasoning that "offering one invites a call
#: that will be rejected downstream" — but nothing downstream rejects it, and
#: omission does not read as a prohibition, it reads as absence. The model then
#: cannot describe or update a surface the SERVER handed it either, because it
#: has no schema for a component it is looking at. Listed, and marked.
SERVER_BUILT = (
    "Server-built. Aleph's own code composes this from live project state; "
    "do not emit one yourself. Listed here so you can read and reason about a "
    "surface you were given."
)


def _load() -> dict:
    return json.loads(CANONICAL.read_text(encoding="utf-8"))


def _load_render() -> dict:
    """The schemas extracted from the catalog the browser actually renders.

    Written by `packages/aleph-a2ui/tools/extract_render_catalog.mjs`, which
    needs Node and `pnpm -C apps/web install`. It is committed rather than
    regenerated here so this script — and `check-catalog-generated.sh`, which
    runs in a Python-only CI job — stay runnable with no JS toolchain. The
    freshness of the extraction is a separate gate:
    `scripts/check-agent-catalog-covers-renderer.sh`.
    """
    return json.loads(RENDER_CATALOG.read_text(encoding="utf-8"))


def render_web_catalog(cat: dict) -> str:
    """`apps/web/src/a2ui/catalog.ts` — the name + action *type* contract.

    The web app fetches the full schema from `GET /v1/a2ui/catalog` at runtime;
    what it needs at compile time is the closed set of names, so a renderer map
    missing an entry is a type error rather than a blank panel.
    """
    names = "\n".join(f'  "{n}",' for n in cat["components"])
    actions = "\n".join(f'  "{a}",' for a in cat["actions"])
    return f"""{BANNER}
// Mirror of `packages/aleph-a2ui/src/aleph_a2ui/catalog.json`. The web app
// fetches the canonical schema from `GET /v1/a2ui/catalog` at startup and
// validates against it; the static lists below are the *type* contract, which
// is what makes a missing renderer a compile error instead of an empty pane.

export const CATALOG_VERSION = "{cat["version"]}";

export const COMPONENT_NAMES = [
{names}
] as const;

export type ComponentName = (typeof COMPONENT_NAMES)[number];

export const ACTION_NAMES = [
{actions}
] as const;

export type ActionName = (typeof ACTION_NAMES)[number];

/**
 * The wire shape of a rendered component. Mirrors the `_comp()` envelope every
 * catalog entry shares — `type`/`id`/`props` required, `data_bindings` and
 * `children` optional — so a renderer destructuring a payload is typed against
 * the same contract the Python validator enforces.
 */
export interface A2UIComponent {{
  type: ComponentName;
  id: string;
  props: Record<string, unknown>;
  data_bindings?: Record<string, unknown>;
  children?: A2UIComponent[];
}}
"""


def _overlay_prop_notes(name: str, cat: dict, properties: dict[str, object]) -> list[str]:
    """Fold `catalog.json`'s hand-written per-prop prose onto the extracted schema.

    STRUCTURE always comes from the renderer; only prose and value vocabularies
    come from here, and only for a prop the renderer actually declares. That
    asymmetry is the whole point. `catalog.json`'s `agent.props` block was a
    third transcription of shapes that live in two other places, and it had
    already drifted — it offered `ApprovalCard.diff_card_id` and
    `ChartCard.dataset_version_id`, which no zod schema declares, so the binder
    would have dropped them in silence, and it omitted every `*_action` prop
    the cards genuinely take.

    Two things survive that are worth keeping and exist nowhere else:
    a `description` on a prop, and the `enum` on the SERVER-side envelope
    schema (`components[x].schema.props.properties`). The server rejects an
    out-of-vocabulary value already; the agent was never told the vocabulary.

    Returns the props described here that the renderer does not declare, so the
    disagreement is reported rather than swallowed.
    """
    entry = cat["components"].get(name) or {}
    sources: list[dict[str, object]] = []
    agent = entry.get("agent")
    if isinstance(agent, dict):
        agent_props = agent.get("props")
        if isinstance(agent_props, dict):
            inner = agent_props.get("properties")
            if isinstance(inner, dict):
                sources.append(inner)
    schema = entry.get("schema")
    if isinstance(schema, dict):
        envelope = ((schema.get("properties") or {}).get("props") or {}).get("properties")
        if isinstance(envelope, dict):
            sources.append(envelope)

    orphans: list[str] = []
    for source in sources:
        for prop, note in source.items():
            if not isinstance(note, dict):
                continue
            target = properties.get(prop)
            if not isinstance(target, dict):
                if prop not in properties:
                    orphans.append(f"{name}.{prop}")
                continue
            for key in ("description", "enum"):
                if key in note and key not in target:
                    target[key] = note[key]
    return sorted(set(orphans))


def render_runtime_catalog(cat: dict, render: dict) -> str:
    """The agent-facing catalog injected by `copilot-runtime`.

    DERIVED, not filtered. This used to expose the ten `catalog.json` entries
    carrying an `agent` block plus nine hand-copied primitives — 19 components,
    against 39 the renderer could draw. The twenty missing ones included every
    input control there is (TextField, CheckBox, ChoicePicker, Slider,
    DateTimeInput), so the assistant could not ask for a form and a plugin could
    not declare a settings screen. Nothing failed; the model simply never
    mentioned a component it had never been shown.

    The component SET and the prop SCHEMAS now come from
    `render_catalog.generated.json`, extracted from `buildAlephCatalog()`
    itself. `catalog.json` supplies only the prose: which components the agent
    is invited to emit (an `agent` block) and what each one is for. A component
    the renderer gains and nobody writes prose for is still exposed — silently
    dropping it is the failure this function exists to end.
    """
    described: dict[str, str] = {}
    server_built: set[str] = set()
    for name, entry in cat["components"].items():
        agent = entry.get("agent")
        if isinstance(agent, dict) and agent.get("description"):
            described[name] = str(agent["description"])
        else:
            server_built.add(name)
    # `primitives` is prose only — `name -> description` — for the basic-catalog
    # components, which have no `catalog.json` schema because they are not
    # Aleph's to define. It used to carry a hand-copied `props` block per entry
    # as well; that block was a third transcription of a shape the renderer
    # already owns, it is no longer read, and it is gone.
    for name, description in cat["primitives"].items():
        if description:
            described[name] = str(description)

    components: dict[str, object] = {}
    orphans: list[str] = []
    for name, schema in render["components"].items():
        parts = [described.get(name), SERVER_BUILT if name in server_built else None]
        description = " ".join(p for p in parts if p)
        entry: dict[str, object] = {}
        if description:
            entry["description"] = description
        entry.update(schema)
        properties = entry.get("properties")
        if isinstance(properties, dict):
            orphans += _overlay_prop_notes(name, cat, properties)
        components[name] = entry

    if orphans:
        # Not fatal, and deliberately so: this is the RENDERER and the server
        # validator disagreeing about a component's props, which is a different
        # defect in a different file. Printing it keeps it from being invisible
        # — the agent block claimed `ApprovalCard.diff_card_id` and
        # `ChartCard.dataset_version_id` for as long as it existed, and the
        # binder drops an undeclared prop without raising.
        print(
            "note: catalog.json describes props the renderer does not declare "
            "(dropped from the agent catalog):\n  " + "\n  ".join(orphans),
            file=sys.stderr,
        )

    payload = {
        "catalogId": cat["agentCatalogId"],
        "$defs": render["$defs"],
        "components": components,
    }
    body = json.dumps(payload, indent=2, ensure_ascii=False)
    return f"""{RUNTIME_BANNER}
/**
 * The catalog the agent is shown: every component
 * `apps/web/src/a2ui/aleph-catalog-v09.tsx` can render, in the A2UI v0.9 wire
 * shape the agent must produce — `{{ id, component, ...props }}`, props inline.
 *
 * Two sources, one output. The component set and the prop schemas are
 * EXTRACTED from the renderer's own zod schemas
 * (`packages/aleph-a2ui/tools/extract_render_catalog.mjs` ->
 * `render_catalog.generated.json`); the descriptions come from
 * `packages/aleph-a2ui/src/aleph_a2ui/catalog.json`, the one file a human
 * edits. So the shapes the agent is told about, the shapes the browser draws
 * and the shapes `aleph_a2ui.catalog.validate_component` accepts cannot drift.
 *
 * `required` and `properties` sit at the top level of each entry deliberately:
 * that is where `@ag-ui/a2ui-toolkit`'s `validateA2UIComponents` looks when the
 * A2UI middleware decides whether to paint a surface or ask the model to try
 * again. Nested under an `allOf` wrapper — the upstream inline-catalog shape —
 * both are invisible and validation quietly degrades to a name check.
 */
export const ALEPH_A2UI_CATALOG = {body} as const;
"""


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="diff only; write nothing")
    args = parser.parse_args()

    cat = _load()
    render = _load_render()
    targets = {
        WEB_CATALOG: render_web_catalog(cat),
        RUNTIME_CATALOG: render_runtime_catalog(cat, render),
    }

    stale: list[str] = []
    for path, content in targets.items():
        current = path.read_text(encoding="utf-8") if path.is_file() else None
        if current == content:
            continue
        rel = path.relative_to(ROOT)
        if args.check:
            stale.append(str(rel))
        else:
            path.write_text(content, encoding="utf-8")
            print(f"wrote {rel}")

    if args.check and stale:
        print(
            "✗ generated catalog files are stale:\n  "
            + "\n  ".join(stale)
            + "\n\n  Edit packages/aleph-a2ui/src/aleph_a2ui/catalog.json, then run:\n"
            "    python scripts/gen_catalog.py",
            file=sys.stderr,
        )
        return 1
    if args.check:
        print(f"✓ generated catalogs match catalog.json ({len(targets)} files)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
