#!/usr/bin/env python3
"""Generate every catalog copy from the one canonical file.

The A2UI catalog was maintained by hand in three places: a 614-line
`catalog.py`, a 65-line `catalog.ts`, and a ~265-line object literal inside
`copilot-runtime/src/server.ts`. Nothing tied them together, and they drifted
in ways that were invisible until an agent hit them:

* `ClaimCard.confidence` contained **no** `"cited"` in any copy — the value both
  wiki writers hardcode, so validating a real card would have rejected it;
* the agent-facing copy offered `"initial"`, which nothing recognises, and
  omitted `"retracted"`, making the WP-6 state unemittable;
* `"dismiss"` was declared dispatchable with no handler behind it.

Those were found and fixed, and `check-catalog-roster.sh` plus
`test_catalog_agreement.py` now catch a *recurrence*. But catching drift is a
weaker guarantee than not being able to drift: this generator makes
`catalog.json` the only file a human edits, and `check-catalog-generated.sh`
fails the build if a generated file no longer matches it.

Run:  python scripts/gen_catalog.py [--check]

`--check` regenerates into memory and diffs, changing nothing — the CI mode.
"""

from __future__ import annotations

import argparse
import json
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parents[1]
CANONICAL = ROOT / "packages/aleph-a2ui/src/aleph_a2ui/catalog.json"
WEB_CATALOG = ROOT / "apps/web/src/a2ui/catalog.ts"
RUNTIME_CATALOG = ROOT / "apps/copilot-runtime/src/catalog.generated.ts"

BANNER = "// GENERATED by scripts/gen_catalog.py from catalog.json — do not edit."


def _load() -> dict:
    return json.loads(CANONICAL.read_text(encoding="utf-8"))


def render_web_catalog(cat: dict) -> str:
    """`apps/web/src/a2ui/catalog.ts` — the name + action *type* contract.

    The web app fetches the full schema from `GET /v1/a2ui/catalog` at runtime;
    what it needs at compile time is the closed set of names, so a renderer map
    missing an entry is a type error rather than a blank panel.
    """
    names = "\n".join(f'  "{n}",' for n in cat["components"])
    actions = "\n".join(f'  "{a}",' for a in cat["actions"])
    return f"""{BANNER}
// Mirror of `packages/aleph-a2ui/src/aleph_a2ui/catalog.json`. The web app
// fetches the canonical schema from `GET /v1/a2ui/catalog` at startup and
// validates against it; the static lists below are the *type* contract, which
// is what makes a missing renderer a compile error instead of an empty pane.

export const CATALOG_VERSION = "{cat["version"]}";

export const COMPONENT_NAMES = [
{names}
] as const;

export type ComponentName = (typeof COMPONENT_NAMES)[number];

export const ACTION_NAMES = [
{actions}
] as const;

export type ActionName = (typeof ACTION_NAMES)[number];

/**
 * The wire shape of a rendered component. Mirrors the `_comp()` envelope every
 * catalog entry shares — `type`/`id`/`props` required, `data_bindings` and
 * `children` optional — so a renderer destructuring a payload is typed against
 * the same contract the Python validator enforces.
 */
export interface A2UIComponent {{
  type: ComponentName;
  id: string;
  props: Record<string, unknown>;
  data_bindings?: Record<string, unknown>;
  children?: A2UIComponent[];
}}
"""


def render_runtime_catalog(cat: dict) -> str:
    """The agent-facing catalog injected by `copilot-runtime`.

    Only components carrying an `agent` block are exposed: an agent cannot be
    asked to emit a surface component the server builds for it, and offering
    one invites a call that will be rejected downstream.
    """
    components: dict[str, dict] = {}
    for name, entry in cat["components"].items():
        if "agent" in entry:
            components[name] = entry["agent"]
    components.update(cat["primitives"])
    payload = {"catalogId": cat["agentCatalogId"], "components": components}
    body = json.dumps(payload, indent=2, ensure_ascii=False)
    return f"""{BANNER}
/**
 * The catalog the agent is shown: Aleph's domain cards plus the A2UI
 * primitives they compose from. Generated from
 * `packages/aleph-a2ui/src/aleph_a2ui/catalog.json`, which is also the source
 * of the Python validator — so the shapes the agent is told about and the
 * shapes the server accepts cannot drift apart.
 */
export const ALEPH_A2UI_CATALOG = {body} as const;
"""


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="diff only; write nothing")
    args = parser.parse_args()

    cat = _load()
    targets = {
        WEB_CATALOG: render_web_catalog(cat),
        RUNTIME_CATALOG: render_runtime_catalog(cat),
    }

    stale: list[str] = []
    for path, content in targets.items():
        current = path.read_text(encoding="utf-8") if path.is_file() else None
        if current == content:
            continue
        rel = path.relative_to(ROOT)
        if args.check:
            stale.append(str(rel))
        else:
            path.write_text(content, encoding="utf-8")
            print(f"wrote {rel}")

    if args.check and stale:
        print(
            "✗ generated catalog files are stale:\n  "
            + "\n  ".join(stale)
            + "\n\n  Edit packages/aleph-a2ui/src/aleph_a2ui/catalog.json, then run:\n"
            "    python scripts/gen_catalog.py",
            file=sys.stderr,
        )
        return 1
    if args.check:
        print(f"✓ generated catalogs match catalog.json ({len(targets)} files)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
