"""Drop the hypotheses tables. The ACH feature did nothing.

Analysis of Competing Hypotheses shipped as three tables, a service, a pane, a
REST router, three agent tools, a card action, an A2UI surface, a dedicated
subagent whose ENTIRE toolset was these three tools, and a skill document telling
the model to drive them. It is deleted — `docs/decisions.md` D16.

The load-bearing half moved rather than going with it. `next_confidence_from_evidence`
and `weight_for_tier` — the claim-confidence state machine the wiki's
`BeliefService` calls on every claim write — lived in this package and now live in
`aleph_belief.confidence`, beside the trust lattice they score. `aleph-core` was
the obvious home and is the wrong one: it is the leaf and cannot import
`TrustTier`.

IRREVERSIBLE IN PRACTICE, and the downgrade says so honestly. It recreates the
tables so a rollback can proceed, but the ROWS are gone; `hypothesis_versions`
also carried an append-only trigger and its function, which the downgrade
restores because a table whose immutability trigger is missing is worse than one
that is absent.


Revision ID: 99531963d0ad
Revises: e71d447a6d8f
Create Date: 2026-08-25 11:32:20.084754+00:00

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "99531963d0ad"
down_revision: str | None = "e71d447a6d8f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_hypothesis_versions_hypothesis_id"), table_name="hypothesis_versions")
    op.drop_index(op.f("ix_hypothesis_versions_project_id"), table_name="hypothesis_versions")
    op.drop_table("hypothesis_versions")
    op.drop_index(op.f("ix_hypotheses_project_id"), table_name="hypotheses")
    op.drop_table("hypotheses")
    op.drop_index(op.f("ix_hypothesis_evidence_hypothesis_id"), table_name="hypothesis_evidence")
    op.drop_index(op.f("ix_hypothesis_evidence_project_id"), table_name="hypothesis_evidence")
    op.drop_table("hypothesis_evidence")
    # `DROP TABLE` takes the trigger with it; the FUNCTION it called outlives the
    # table and would sit in the schema forever, matching nothing.
    op.execute("DROP FUNCTION IF EXISTS hypothesis_versions_immutable()")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "hypothesis_evidence",
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("created_by", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("trace_id", sa.VARCHAR(length=128), autoincrement=False, nullable=True),
        sa.Column("ledger_event_id", sa.UUID(), autoincrement=False, nullable=True),
        sa.Column("project_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("hypothesis_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("hypothesis_version_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("stance", sa.VARCHAR(length=16), autoincrement=False, nullable=False),
        sa.Column("evidence_kind", sa.VARCHAR(length=32), autoincrement=False, nullable=False),
        sa.Column("target_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column(
            "weight",
            sa.DOUBLE_PRECISION(precision=53),
            server_default=sa.text("'1'::double precision"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "note",
            sa.TEXT(),
            server_default=sa.text("''::text"),
            autoincrement=False,
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("hypothesis_evidence_pkey")),
    )
    op.create_index(
        op.f("ix_hypothesis_evidence_project_id"),
        "hypothesis_evidence",
        ["project_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_hypothesis_evidence_hypothesis_id"),
        "hypothesis_evidence",
        ["hypothesis_id"],
        unique=False,
    )
    op.create_table(
        "hypotheses",
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("created_by", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("trace_id", sa.VARCHAR(length=128), autoincrement=False, nullable=True),
        sa.Column("ledger_event_id", sa.UUID(), autoincrement=False, nullable=True),
        sa.Column("project_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("short_id", sa.VARCHAR(length=16), autoincrement=False, nullable=False),
        sa.Column("title", sa.VARCHAR(length=512), autoincrement=False, nullable=False),
        sa.Column("statement", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column(
            "confidence",
            sa.VARCHAR(length=24),
            server_default=sa.text("'under_investigation'::character varying"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.VARCHAR(length=16),
            server_default=sa.text("'active'::character varying"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("current_version_id", sa.UUID(), autoincrement=False, nullable=True),
        sa.Column(
            "last_evidence_change_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("hypotheses_pkey")),
        sa.UniqueConstraint(
            "short_id",
            name=op.f("hypotheses_short_id_key"),
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
    )
    op.create_index(op.f("ix_hypotheses_project_id"), "hypotheses", ["project_id"], unique=False)
    op.create_table(
        "hypothesis_versions",
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("project_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("hypothesis_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("version_no", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("statement", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("confidence", sa.VARCHAR(length=24), autoincrement=False, nullable=False),
        sa.Column(
            "rationale",
            sa.TEXT(),
            server_default=sa.text("''::text"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("author_kind", sa.VARCHAR(length=16), autoincrement=False, nullable=False),
        sa.Column("author_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("parent_version_id", sa.UUID(), autoincrement=False, nullable=True),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("trace_id", sa.VARCHAR(length=128), autoincrement=False, nullable=True),
        sa.Column("ledger_event_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("hypothesis_versions_pkey")),
        sa.UniqueConstraint(
            "hypothesis_id",
            "version_no",
            name=op.f("uq_hypothesis_version_no"),
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
    )
    op.create_index(
        op.f("ix_hypothesis_versions_project_id"),
        "hypothesis_versions",
        ["project_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_hypothesis_versions_hypothesis_id"),
        "hypothesis_versions",
        ["hypothesis_id"],
        unique=False,
    )
    # Restore the append-only guard with the table. A version table whose
    # immutability trigger is missing looks fine and silently permits the edit
    # the trigger exists to refuse.
    op.execute(
        "CREATE OR REPLACE FUNCTION hypothesis_versions_immutable() RETURNS trigger AS $$ "
        "BEGIN RAISE EXCEPTION 'hypothesis_versions is append-only'; END; $$ LANGUAGE plpgsql"
    )
    op.execute(
        "CREATE TRIGGER hypothesis_versions_no_update BEFORE UPDATE ON hypothesis_versions "
        "FOR EACH ROW EXECUTE FUNCTION hypothesis_versions_immutable()"
    )
    op.execute(
        "CREATE TRIGGER hypothesis_versions_no_delete BEFORE DELETE ON hypothesis_versions "
        "FOR EACH ROW EXECUTE FUNCTION hypothesis_versions_immutable()"
    )
    # ### end Alembic commands ###
