"""a1b_plugins_table

Revision ID: 2af5069932e1
Revises: rs9_confidence_vocab
Create Date: 2026-08-22 11:32:08.308141+00:00

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "2af5069932e1"
down_revision: str | None = "rs9_confidence_vocab"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "plugins",
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("major_version", sa.Integer(), server_default="1", nullable=False),
        sa.Column("source_kind", sa.String(length=16), nullable=False),
        sa.Column("instructions", sa.Text(), server_default="", nullable=False),
        sa.Column("code", sa.Text(), nullable=True),
        sa.Column(
            "provides", postgresql.JSONB(astext_type=sa.Text()), server_default="[]", nullable=False
        ),
        sa.Column(
            "requires", postgresql.JSONB(astext_type=sa.Text()), server_default="[]", nullable=False
        ),
        sa.Column(
            "config_schema",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        ),
        sa.Column("state", sa.String(length=16), server_default="installed", nullable=False),
        sa.Column("failure_reason", sa.String(length=2048), nullable=True),
        sa.Column("installed_by", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.Uuid(), nullable=False),
        sa.Column("trace_id", sa.String(length=128), nullable=True),
        sa.Column("ledger_event_id", sa.Uuid(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "project_id", "name", "major_version", name="uq_plugins_project_name_major"
        ),
    )
    op.create_index(op.f("ix_plugins_project_id"), "plugins", ["project_id"], unique=False)
    op.create_index("ix_plugins_project_state", "plugins", ["project_id", "state"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_plugins_project_state", table_name="plugins")
    op.drop_index(op.f("ix_plugins_project_id"), table_name="plugins")
    op.drop_table("plugins")
    # ### end Alembic commands ###
