"""wiki schema governance

Gives the wiki the governance layer the hermes-agent `llm-wiki` skill defines
and `~/wiki/ai-research` is built on. Two parts:

`wiki_schemas` — one row per project holding that project's domain statement,
category list, controlled tag taxonomy and page thresholds. Per-project because
a tag taxonomy is a claim about a domain; a shared one degrades into the union
of every domain, which constrains none of them.

New `wiki_pages` columns mirroring the hermes frontmatter field-for-field, so a
vault round-trips through Obsidian without a translation layer: `category`,
`page_type`, `tags`, `related`, `confidence`, `contested`, `contradictions`.

They are columns rather than markdown because each is something the system must
filter, group or lint on, and parsing every body to answer "which pages are
contested" is not a query. `page_type` is deliberately distinct from the
existing `page_kind`: `page_kind` records how Aleph produced the page (source
ingest, stub, synthesis), `page_type` records what kind of knowledge it holds
(concept, entity, comparison, query, hub).

Everything is nullable or defaulted, so existing rows stay readable and are
backfilled separately rather than by this migration guessing at categories.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "ee0b492b2778"
down_revision: str | None = "stubs_not_drafts"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "wiki_schemas",
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("payload_jsonb", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.Uuid(), nullable=False),
        sa.Column("access_scope", sa.String(length=64), server_default="project", nullable=False),
        sa.Column("trace_id", sa.String(length=128), nullable=True),
        sa.Column("ledger_event_id", sa.Uuid(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("project_id", name="uq_wiki_schemas_project"),
    )
    op.create_index(
        op.f("ix_wiki_schemas_project_id"), "wiki_schemas", ["project_id"], unique=False
    )
    op.add_column("wiki_pages", sa.Column("category", sa.String(length=64), nullable=True))
    op.add_column("wiki_pages", sa.Column("page_type", sa.String(length=16), nullable=True))
    op.add_column(
        "wiki_pages",
        sa.Column(
            "tags", postgresql.JSONB(astext_type=sa.Text()), server_default="[]", nullable=False
        ),
    )
    op.add_column(
        "wiki_pages",
        sa.Column(
            "related", postgresql.JSONB(astext_type=sa.Text()), server_default="[]", nullable=False
        ),
    )
    op.add_column("wiki_pages", sa.Column("confidence", sa.String(length=8), nullable=True))
    op.add_column(
        "wiki_pages", sa.Column("contested", sa.Boolean(), server_default="false", nullable=False)
    )
    op.add_column(
        "wiki_pages",
        sa.Column(
            "contradictions",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="[]",
            nullable=False,
        ),
    )
    op.create_index(op.f("ix_wiki_pages_category"), "wiki_pages", ["category"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_wiki_pages_category"), table_name="wiki_pages")
    op.drop_column("wiki_pages", "contradictions")
    op.drop_column("wiki_pages", "contested")
    op.drop_column("wiki_pages", "confidence")
    op.drop_column("wiki_pages", "related")
    op.drop_column("wiki_pages", "tags")
    op.drop_column("wiki_pages", "page_type")
    op.drop_column("wiki_pages", "category")
    op.drop_index(op.f("ix_wiki_schemas_project_id"), table_name="wiki_schemas")
    op.drop_table("wiki_schemas")
    # ### end Alembic commands ###
