"""Agent Protocol threads: Aleph hosts the five routes deepagents drives.

`docs/decisions.md` D17. `AsyncSubAgentMiddleware` talks to "any server that
implements the Agent Protocol", and the surface it uses is five routes over
threads and runs. Hosting them means Aleph gets the five supervisor tools, the
`async_tasks` state channel that survives context compaction, and the prompt
rules against self-polling, instead of writing a delegation framework.

`agent_threads` is a new table rather than a reuse of `assistant_threads`, whose
`session_id` is NOT NULL: a delegated subagent run is not a user chat session,
and reusing it would mean minting a fake session per delegation.

`graph_id` is nullable because `threads.create()` takes no arguments —
`assistant_id` only arrives on the first `runs.create`. A thread exists briefly
with no graph, and a NOT NULL column would have to be filled with a lie.

`agent_runs.agent_thread_id` is nullable because most runs are not delegations.
It exists because `update` starts a NEW run on the SAME thread, so runs must be
groupable by thread.


Revision ID: 2d0e7142a268
Revises: 99531963d0ad
Create Date: 2026-08-25 12:24:18.835204+00:00

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "2d0e7142a268"
down_revision: str | None = "99531963d0ad"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "agent_threads",
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("graph_id", sa.String(length=64), nullable=True),
        sa.Column("parent_agent_run_id", sa.Uuid(), nullable=True),
        sa.Column(
            "values_jsonb",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.Uuid(), nullable=False),
        sa.Column("trace_id", sa.String(length=128), nullable=True),
        sa.Column("ledger_event_id", sa.Uuid(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_agent_threads_parent_agent_run_id"),
        "agent_threads",
        ["parent_agent_run_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_agent_threads_project_id"), "agent_threads", ["project_id"], unique=False
    )
    op.add_column("agent_runs", sa.Column("agent_thread_id", sa.Uuid(), nullable=True))
    op.create_index(
        op.f("ix_agent_runs_agent_thread_id"), "agent_runs", ["agent_thread_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_agent_runs_agent_thread_id"), table_name="agent_runs")
    op.drop_column("agent_runs", "agent_thread_id")
    op.drop_index(op.f("ix_agent_threads_project_id"), table_name="agent_threads")
    op.drop_index(op.f("ix_agent_threads_parent_agent_run_id"), table_name="agent_threads")
    op.drop_table("agent_threads")
    # ### end Alembic commands ###
