"""mep4_gateway_endpoints

Revision ID: e71d447a6d8f
Revises: 755b0778b58a
Create Date: 2026-08-22 16:54:58.000703+00:00

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e71d447a6d8f"
down_revision: str | None = "755b0778b58a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "gateway_endpoints",
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("base_url", sa.String(length=2048), nullable=False),
        sa.Column("api_key_cipher", sa.LargeBinary(), nullable=True),
        sa.Column("cipher_scheme", sa.String(length=32), nullable=True),
        sa.Column("key_version", sa.String(length=16), nullable=True),
        sa.Column("is_default", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("last_probe_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_probe_ok", sa.Boolean(), nullable=True),
        sa.Column("last_probe_error", sa.String(length=2048), nullable=True),
        sa.Column("last_probe_model_count", sa.Integer(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.Uuid(), nullable=False),
        sa.Column("trace_id", sa.String(length=128), nullable=True),
        sa.Column("ledger_event_id", sa.Uuid(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("project_id", "name", name="uq_gateway_endpoint_project_name"),
    )
    op.create_index(
        op.f("ix_gateway_endpoints_project_id"), "gateway_endpoints", ["project_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_gateway_endpoints_project_id"), table_name="gateway_endpoints")
    op.drop_table("gateway_endpoints")
    # ### end Alembic commands ###
