"""a4_plugin_settings

Revision ID: 755b0778b58a
Revises: 2af5069932e1
Create Date: 2026-08-22 11:59:50.624919+00:00

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "755b0778b58a"
down_revision: str | None = "2af5069932e1"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "plugin_settings",
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("plugin_id", sa.String(), nullable=False),
        sa.Column(
            "values", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.Uuid(), nullable=False),
        sa.Column("trace_id", sa.String(length=128), nullable=True),
        sa.Column("ledger_event_id", sa.Uuid(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("project_id", "plugin_id", name="uq_plugin_settings_project_plugin"),
    )
    op.create_index(
        op.f("ix_plugin_settings_project_id"), "plugin_settings", ["project_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_plugin_settings_project_id"), table_name="plugin_settings")
    op.drop_table("plugin_settings")
    # ### end Alembic commands ###
