"""wiki curator page_merge_proposals

Revision ID: a8b39f52d713
Revises: realtime_notify_triggers
Create Date: 2026-06-26 18:23:00.093916+00:00

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a8b39f52d713"
down_revision: str | None = "realtime_notify_triggers"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "page_merge_proposals",
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("source_page_id", sa.Uuid(), nullable=False),
        sa.Column("target_page_id", sa.Uuid(), nullable=False),
        sa.Column("rationale", sa.String(length=2048), server_default="", nullable=False),
        sa.Column("similarity", sa.Float(), server_default="0", nullable=False),
        sa.Column("status", sa.String(length=16), server_default="pending", nullable=False),
        sa.Column("approval_decision_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.Uuid(), nullable=False),
        sa.Column("access_scope", sa.String(length=64), server_default="project", nullable=False),
        sa.Column("trace_id", sa.String(length=128), nullable=True),
        sa.Column("ledger_event_id", sa.Uuid(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_page_merge_proposals_project_id"),
        "page_merge_proposals",
        ["project_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_page_merge_proposals_source_page_id"),
        "page_merge_proposals",
        ["source_page_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_page_merge_proposals_target_page_id"),
        "page_merge_proposals",
        ["target_page_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_page_merge_proposals_target_page_id"), table_name="page_merge_proposals")
    op.drop_index(op.f("ix_page_merge_proposals_source_page_id"), table_name="page_merge_proposals")
    op.drop_index(op.f("ix_page_merge_proposals_project_id"), table_name="page_merge_proposals")
    op.drop_table("page_merge_proposals")
    # ### end Alembic commands ###
