/**
 * Extract the AGENT-FACING catalog from the catalog the browser actually renders.
 *
 * The two lists used to be written separately and they disagreed by twenty
 * components. `buildAlephCatalog()` in `apps/web/src/a2ui/aleph-catalog-v09.tsx`
 * registers every component implementation the renderer holds; the catalog
 * handed to the model (`apps/copilot-runtime/src/catalog.generated.ts`) named
 * 19 of them, chosen by a filter in `scripts/gen_catalog.py` over the ten
 * `catalog.json` entries that happened to carry an `agent` block, plus nine
 * hand-copied primitives. Every input control the renderer supports —
 * TextField, CheckBox, ChoicePicker, Slider, DateTimeInput — was in the first
 * list and absent from the second, so the assistant could not ask for a form
 * and a plugin could not declare a settings screen. Nothing reported a problem:
 * a component the catalog omits is not an error, it is a component the model
 * never mentions.
 *
 * The fix is derivation. This script boots the real module graph, calls the
 * real `buildAlephCatalog()`, and reads the zod schemas the Generic Binder
 * resolves against — so "what the agent is told" is a projection of "what the
 * browser can draw" and the two cannot drift.
 *
 *   node packages/aleph-a2ui/tools/extract_render_catalog.mjs [--check|--print]
 *
 * Default writes the artifact. `--check` writes nothing and exits 1 if the
 * committed artifact is stale. `--print` writes to stdout instead, which is how
 * `scripts/check-agent-catalog-covers-renderer.sh` compares a LIVE extraction
 * against the shipped agent catalog rather than trusting either copy.
 *
 * WHY VITE. The schemas are zod VALUES built at module-evaluation time, so
 * every extractor upstream ships — `extractCatalogComponentSchemas`
 * (`@copilotkit/a2ui-renderer`) and `MessageProcessor.generateInlineCatalog`
 * (`@a2ui/web_core`) — needs the live catalog object, not a source file.
 * Getting one means importing a `.tsx` that pulls in React, a path alias and
 * 22 view components, which plain `node` cannot load. Vite's `ssrLoadModule` is
 * the same transform pipeline the app itself uses, so what is extracted here is
 * what the browser gets.
 *
 * WHY NOT THE UPSTREAM EXTRACTORS THEMSELVES. `@copilotkit/a2ui-renderer` is a
 * transitive dependency and does not resolve from `apps/web`; adding it would
 * be a new dependency for a build-time script. `generateInlineCatalog` is
 * reachable (via `getClientCapabilities({ includeInlineCatalogs: true })`) and
 * was tried first — it emits refs that do not resolve. It runs
 * `zod-to-json-schema` at its default `$refStrategy`, which replaces a repeated
 * subschema with a JSON Pointer to the first place it appeared, and THEN
 * rewrites `accessibility` — where the first `DynamicString` happens to appear
 * — into an external `$ref`. Fifty-three pointers across the catalog then aim
 * at `#/properties/accessibility/properties/label/anyOf/0`, a node no longer in
 * the document. This file therefore does what both upstream helpers do, in the
 * order that works: expand fully (`$refStrategy: "none"`), collapse the `REF:`
 * markers, and carry one shared `$defs`.
 *
 * `vite`, and `zod-to-json-schema` bound to the same zod 3 the catalog is built
 * with, are resolved through `apps/web` and `@a2ui/web_core` respectively:
 * nothing is installed beside this script and the repo root has no top-level
 * `node_modules`.
 */
import { createRequire } from "node:module";
import { pathToFileURL } from "node:url";
import fs from "node:fs";
import path from "node:path";

const ROOT = path.resolve(path.dirname(new URL(import.meta.url).pathname), "../../..");
const WEB = path.join(ROOT, "apps/web");
const OUT = path.join(ROOT, "packages/aleph-a2ui/src/aleph_a2ui/render_catalog.generated.json");

const BANNER =
  "GENERATED by packages/aleph-a2ui/tools/extract_render_catalog.mjs from " +
  "apps/web/src/a2ui/aleph-catalog-v09.tsx — do not edit.";

/**
 * Props every component carries, lifted out of all forty per-component schemas
 * into `$defs/ComponentCommon`. Repeating the same ~700 bytes of
 * `accessibility` and `weight` prose once per component nearly doubled a
 * document that is injected into the model's context on every run.
 */
const HOISTED = new Set(["accessibility", "weight"]);

const webRequire = createRequire(path.join(WEB, "package.json"));
const coreRequire = createRequire(webRequire.resolve("@a2ui/web_core/v0_9"));

async function loadDep(req, spec) {
  const mod = await import(pathToFileURL(req.resolve(spec)).href);
  return mod.default ?? mod;
}

function readCommonTypes() {
  // `common_types.json` ships inside `@a2ui/web_core`. Reading it out of the
  // installed package rather than copying it is what keeps the `$defs` this
  // catalog references identical to the ones the renderer validates against.
  const schemas = path.join(
    path.dirname(coreRequire.resolve("@a2ui/web_core/v0_9")),
    "schemas/common_types.json",
  );
  const defs = JSON.parse(fs.readFileSync(schemas, "utf8")).$defs;
  // `FunctionCall.oneOf` points at `catalog.json#/$defs/anyFunction`, a
  // document nothing here ships. Most validators do not complain about an
  // unresolvable `$ref` until a payload reaches it, so it is removed rather
  // than left as a trap for the first agent that emits a function call.
  if (defs.FunctionCall) delete defs.FunctionCall.oneOf;
  return defs;
}

/**
 * Collapse the `REF:` markers `@a2ui/web_core` encodes in zod descriptions.
 *
 * A shared type is declared in zod as `.describe("REF:common_types.json#/$defs/
 * DynamicString|the real description")`. Mirrors `MessageProcessor.processRefs`
 * — same contract, so a catalog change upstream lands here — except the ref is
 * rewritten to a local `#/$defs/...` pointer, since this document carries its
 * own copy of the common types and is validated standalone by
 * `aleph_a2ui.catalog.validate_component`.
 */
function collapseRefs(node, defs) {
  if (Array.isArray(node)) return node.map((n) => collapseRefs(n, defs));
  if (node === null || typeof node !== "object") return node;

  const marker = node.description;
  if (typeof marker === "string" && marker.startsWith("REF:")) {
    const [ref, ...rest] = marker.slice(4).split("|");
    const name = ref.split("/").pop();
    const local = ref.startsWith("common_types.json#/$defs/") ? `#/$defs/${name}` : ref;
    const desc = rest.join("|");
    // Keep the description only when it says something the `$defs` entry does
    // not. A prop with no `.describe()` of its own inherits the shared type's
    // generic line, which lands as `"description": "Represents a string"` on
    // sixty props and tells the model nothing it cannot see from the `$ref`.
    const generic = defs[name]?.description;
    return desc && desc !== generic ? { $ref: local, description: desc } : { $ref: local };
  }

  const out = {};
  for (const [k, v] of Object.entries(node)) out[k] = collapseRefs(v, defs);
  return out;
}

/**
 * One renderable component -> one flat JSON Schema over the A2UI v0.9 WIRE
 * shape: `{ id, component, ...props }` with props inline and no `props`
 * envelope.
 *
 * Flat, and not the upstream `allOf: [{$ref: ComponentCommon}, {...}]` wrapper,
 * for a measured reason: `@ag-ui/a2ui-toolkit`'s `validateA2UIComponents` —
 * the validator the A2UI middleware runs before it paints, and the one driving
 * its retry loop — reads `schema.required` and `schema.properties` off the TOP
 * level of each catalog entry. Under the `allOf` wrapper both are undefined and
 * validation degrades to "is this component name known" without saying so.
 * Flattening is what turns the catalog from a name list into an enforced
 * contract, and it is the same shape `aleph_a2ui.catalog.validate_component`
 * validates against — one document, three consumers.
 */
function flatten(name, zodSchema, defs) {
  const collapsed = collapseRefs(zodSchema, defs);
  const properties = { id: { $ref: "#/$defs/ComponentId" }, component: { const: name } };
  for (const [prop, schema] of Object.entries(collapsed.properties ?? {})) {
    if (HOISTED.has(prop)) continue;
    properties[prop] = schema;
  }
  const required = [
    "id",
    "component",
    ...(collapsed.required ?? []).filter((r) => !HOISTED.has(r)),
  ];
  return { type: "object", properties, required };
}

async function extract() {
  const { createServer } = await loadDep(webRequire, "vite");
  const ztjs = await loadDep(coreRequire, "zod-to-json-schema");
  const zodToJsonSchema = ztjs.zodToJsonSchema ?? ztjs;

  const server = await createServer({
    configFile: false,
    root: WEB,
    logLevel: "silent",
    server: { middlewareMode: true, watch: null, hmr: false },
    resolve: { alias: { "@": path.join(WEB, "src") } },
    appType: "custom",
  });
  try {
    const mod = await server.ssrLoadModule("/src/a2ui/aleph-catalog-v09.tsx");
    const catalog = mod.buildAlephCatalog();
    const defs = readCommonTypes();
    const components = {};
    for (const name of [...catalog.components.keys()].sort()) {
      const api = catalog.components.get(name);
      components[name] = flatten(
        name,
        zodToJsonSchema(api.schema, { target: "jsonSchema2019-09", $refStrategy: "none" }),
        defs,
      );
    }
    // Function NAMES, not schemas. The collision check in
    // `aleph_a2ui.plugin_catalogs` refuses a plugin whose component *or
    // function* name is already core's, and it cannot do the second half from
    // a list nobody maintains — the twenty-five basic-catalog functions
    // (`formatDate`, `equals`, `openUrl`, ...) exist only inside
    // `@a2ui/react`'s `basicCatalog`. Deriving them here is the same rule the
    // component list already follows: what the agent is told is a projection
    // of what the browser can draw.
    const functions = [...catalog.functions.keys()].sort();
    return { $comment: BANNER, catalogId: catalog.id, $defs: defs, components, functions };
  } finally {
    await server.close();
  }
}

const args = new Set(process.argv.slice(2));
const payload = JSON.stringify(await extract(), null, 2) + "\n";

if (args.has("--print")) {
  process.stdout.write(payload);
} else if (args.has("--check")) {
  const current = fs.existsSync(OUT) ? fs.readFileSync(OUT, "utf8") : null;
  if (current === payload) {
    console.log(`✓ ${path.relative(ROOT, OUT)} matches the render catalog`);
  } else {
    console.error(
      `✗ ${path.relative(ROOT, OUT)} is stale.\n` +
        "  The renderer's catalog changed. Re-extract, then regenerate:\n" +
        "    node packages/aleph-a2ui/tools/extract_render_catalog.mjs\n" +
        "    uv run python scripts/gen_catalog.py",
    );
    process.exit(1);
  }
} else {
  fs.writeFileSync(OUT, payload);
  console.log(`wrote ${path.relative(ROOT, OUT)}`);
}
